# E-Commerce Order Analytics System

## Step 2: Data Understanding & Exploratory Data Analysis

At this stage, I will analyze the structure and quality of the raw e-commerce data without any data cleaning.

The database consists of four primary tables:

1. Users
2. Products
3. Orders
4. Order Items

The key aims at this stage include the following:

- Loading all raw CSV files
- Analyzing the number of rows and columns
- Checking the column names and types
- Identifying missing values
- Analyzing duplicate entries
- Finding unique values
- Identifying table connections
- Detecting data quality issues

The raw data will remain untouched at this stage.

## 2.1 Import Required Libraries

I will use Pandas for loading and analyzing the CSV files.
I will also use NumPy for basic numerical operations.

In [2]:
# Import Pandas for data analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Display all columns when viewing DataFrames
pd.set_option("display.max_columns", None)

# Display floating-point numbers with 2 decimal places
pd.set_option("display.float_format", "{:.2f}".format)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# ============================================================
# STEP 2.2 - LOAD RAW DATA
# ============================================================

# Define the path of each raw CSV file.
# ".." means go one folder back from the notebooks folder.

orders_path = "../data/raw/orders.csv"
order_items_path = "../data/raw/order_items.csv"
products_path = "../data/raw/products.csv"
users_path = "../data/raw/users.csv"


# Read the CSV files using Pandas

orders = pd.read_csv(orders_path)

order_items = pd.read_csv(order_items_path)

products = pd.read_csv(products_path)

users = pd.read_csv(users_path)


# Print a confirmation message

print("All four CSV files loaded successfully.")

All four CSV files loaded successfully.

In [4]:
# ============================================================
# STEP 2.3 - CHECK DATASET SIZE
# ============================================================

# .shape returns:
# (number of rows, number of columns)

print("Orders Shape:", orders.shape)

print("Order Items Shape:", order_items.shape)

print("Products Shape:", products.shape)

print("Users Shape:", users.shape)

Orders Shape: (20000, 5)
Order Items Shape: (43525, 7)
Products Shape: (2000, 6)
Users Shape: (10000, 6)

In [5]:
# ============================================================
# STEP 2.4 - VIEW FIRST 5 RECORDS
# ============================================================

print("ORDERS")
display(orders.head())

print("ORDER ITEMS")
display(order_items.head())

print("PRODUCTS")
display(products.head())

print("USERS")
display(users.head())

ORDERS

    order_id  user_id                  order_date order_status  total_amount
0  O00000001  U009310  2025-09-09T14:52:37.292731   processing        689.66
1  O00000002  U003247  2025-04-15T01:18:27.193404    completed       1666.85
2  O00000003  U007252  2025-04-27T15:37:48.008624   processing        665.06
3  O00000004  U008986  2025-10-04T20:35:22.204857    cancelled        689.50
4  O00000005  U008537  2024-11-13T08:15:18.498252    cancelled        860.50

ORDER ITEMS

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
0,I00000001,O00000001,P001758,U009310,2,8.07,16.14
1,I00000002,O00000001,P001119,U009310,1,74.08,74.08
2,I00000003,O00000001,P001794,U009310,1,576.97,576.97
3,I00000004,O00000001,P001038,U009310,1,22.47,22.47
4,I00000005,O00000002,P000859,U003247,1,422.22,422.22

PRODUCTS

  product_id     product_name        category    brand  price  rating
0    P000001         Astra Be        Clothing    Astra 157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech  21.46    3.87
2    P000003     Acme Discuss          Sports     Acme 265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus 541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra 198.00    3.97

USERS

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29

## 2.5 Check Column Names

In this step, I will check the column names of all four tables.

Understanding the columns is important because these columns will later be used for:
- Data cleaning
- Validation
- Joining tables
- SQL queries
- Business analysis

In [6]:
# ============================================================
# STEP 2.5 - CHECK COLUMN NAMES
# ============================================================

# Print all column names from the Orders table
print("Orders Columns:")
print(orders.columns.tolist())


# Print all column names from the Order Items table
print("\nOrder Items Columns:")
print(order_items.columns.tolist())


# Print all column names from the Products table
print("\nProducts Columns:")
print(products.columns.tolist())


# Print all column names from the Users table
print("\nUsers Columns:")
print(users.columns.tolist())

Orders Columns:
['order_id', 'user_id', 'order_date', 'order_status', 'total_amount']

Order Items Columns:
['order_item_id', 'order_id', 'product_id', 'user_id', 'quantity', 'item_price', 'item_total']

Products Columns:
['product_id', 'product_name', 'category', 'brand', 'price', 'rating']

Users Columns:
['user_id', 'name', 'email', 'gender', 'city', 'signup_date']

## 2.6 Verify Data Types

The data type informs us of the type of data in each column.

For instance:
- IDs are normally text data
- Quantity is numeric
- Price is numeric
- Dates need to eventually be in the datetime format

This is the point where I am just verifying the data types.
The data conversions will be done in the cleaning phase.

In [8]:
# ============================================================
# STEP 2.6 - CHECK DATA TYPES (CLEAN VIEW)
# ============================================================

print("ORDERS")
display(orders.dtypes.to_frame("Data Type"))

print("\nORDER ITEMS")
display(order_items.dtypes.to_frame("Data Type"))

print("\nPRODUCTS")
display(products.dtypes.to_frame("Data Type"))

print("\nUSERS")
display(users.dtypes.to_frame("Data Type"))

ORDERS

             Data Type
order_id        object
user_id         object
order_date      object
order_status    object
total_amount   float64

ORDER ITEMS

              Data Type
order_item_id    object
order_id         object
product_id       object
user_id          object
quantity          int64
item_price      float64
item_total      float64

PRODUCTS

             Data Type
product_id      object
product_name    object
category        object
brand           object
price          float64
rating         float64

USERS

            Data Type
user_id        object
name           object
email          object
gender         object
city           object
signup_date    object

In [9]:
# ============================================================
# STEP 2.7 - CHECK MISSING VALUES
# ============================================================

print("ORDERS")
display(orders.isnull().sum().to_frame("Missing Values"))

print("\nORDER ITEMS")
display(order_items.isnull().sum().to_frame("Missing Values"))

print("\nPRODUCTS")
display(products.isnull().sum().to_frame("Missing Values"))

print("\nUSERS")
display(users.isnull().sum().to_frame("Missing Values"))

ORDERS

              Missing Values
order_id                   0
user_id                    0
order_date                 0
order_status               0
total_amount               0

ORDER ITEMS

               Missing Values
order_item_id               0
order_id                    0
product_id                  0
user_id                     0
quantity                    0
item_price                  0
item_total                  0

PRODUCTS

              Missing Values
product_id                 0
product_name               0
category                   0
brand                      0
price                      0
rating                     0

USERS

             Missing Values
user_id                   0
name                      0
email                     0
gender                    0
city                      0
signup_date               0

## 2.8 Check Duplicate Records

Duplicate records can cause incorrect calculations and business insights.

For example, duplicate order records can increase revenue or order counts incorrectly.

In this step, I will check whether completely identical rows are present in any of the four tables.

In [10]:
# ============================================================
# STEP 2.8 - CHECK DUPLICATE RECORDS
# ============================================================

# Count completely duplicated rows in the Orders table
print("Duplicate Orders:", orders.duplicated().sum())


# Count completely duplicated rows in the Order Items table
print("Duplicate Order Items:", order_items.duplicated().sum())


# Count completely duplicated rows in the Products table
print("Duplicate Products:", products.duplicated().sum())


# Count completely duplicated rows in the Users table
print("Duplicate Users:", users.duplicated().sum())

Duplicate Orders: 0
Duplicate Order Items: 0
Duplicate Products: 0
Duplicate Users: 0

In [11]:

# STEP 2.9 - CHECK DUPLICATE PRIMARY IDs


print(
    "Duplicate Order IDs:",
    orders["order_id"].duplicated().sum()
)

print(
    "Duplicate Order Item IDs:",
    order_items["order_item_id"].duplicated().sum()
)

print(
    "Duplicate Product IDs:",
    products["product_id"].duplicated().sum()
)

print(
    "Duplicate User IDs:",
    users["user_id"].duplicated().sum()
)

Duplicate Order IDs: 0
Duplicate Order Item IDs: 0
Duplicate Product IDs: 0
Duplicate User IDs: 0

## 2.10 Verify Referential Integrity

The e-commerce database is tied together through IDs.

Expected referential integrity relationships:

- `orders.user_id` must be found in `users.user_id`
- `order_items.order_id` must be found in `orders.order_id`
- `order_items.product_id` must be found in `products.product_id`

I will verify if there are any children records with IDs that don’t exist in the corresponding parent table.

In [12]:
# ============================================================
# STEP 2.10 - CHECK REFERENTIAL INTEGRITY
# ============================================================

# ------------------------------------------------------------
# 1. Check orders -> users relationship
# ------------------------------------------------------------

# Find orders whose user_id does not exist in users table
invalid_order_users = orders[
    ~orders["user_id"].isin(users["user_id"])
]

print(
    "Orders with invalid user_id:",
    len(invalid_order_users)
)


# ------------------------------------------------------------
# 2. Check order_items -> orders relationship
# ------------------------------------------------------------

# Find order items whose order_id does not exist in orders table
invalid_item_orders = order_items[
    ~order_items["order_id"].isin(orders["order_id"])
]

print(
    "Order items with invalid order_id:",
    len(invalid_item_orders)
)


# ------------------------------------------------------------
# 3. Check order_items -> products relationship
# ------------------------------------------------------------

# Find order items whose product_id does not exist in products table
invalid_item_products = order_items[
    ~order_items["product_id"].isin(products["product_id"])
]

print(
    "Order items with invalid product_id:",
    len(invalid_item_products)
)

Orders with invalid user_id: 0
Order items with invalid order_id: 0
Order items with invalid product_id: 0

## 2.11 Validate Item Total

The `item_total` is the total price for each individual product.

I will validate whether:

item_total = quantity × item_price

This test will allow us to detect mistakes in our raw data.

I will not make any changes to the initial raw data at this stage.

In [13]:
# ============================================================
# STEP 2.11 - VALIDATE ITEM TOTAL
# ============================================================

# Calculate the expected item total
# without modifying the original order_items DataFrame

calculated_item_total = (
    order_items["quantity"] *
    order_items["item_price"]
)


# Calculate the difference between:
# Existing item_total
# and
# Calculated item total

total_difference = (
    order_items["item_total"] -
    calculated_item_total
)


# Find rows where the difference is greater than 0.01
# We use 0.01 because prices are generally measured in decimals.

incorrect_item_totals = order_items[
    ~np.isclose(
        order_items["item_total"],
        calculated_item_total,
        atol=0.01
    )
]


# Display the number of inconsistent records

print(
    "Rows with inconsistent item_total:",
    len(incorrect_item_totals)
)

Rows with inconsistent item_total: 0

## 2.12 Identify Numeric Errors

Quantities and monetary values need to be checked for invalid values.

I will look out for:

- Quantity being less than or equal to zero
- Negative price of the items
- Negative total cost of the orders

At this point, I am simply trying to identify issues.
I will not alter or delete any entries.

In [14]:
# ============================================================
# STEP 2.12 - CHECK INVALID NUMERIC VALUES
# ============================================================


# ------------------------------------------------------------
# Check quantity
# ------------------------------------------------------------

invalid_quantity = order_items[
    order_items["quantity"] <= 0
]

print(
    "Order items with quantity <= 0:",
    len(invalid_quantity)
)


# ------------------------------------------------------------
# Check item price
# ------------------------------------------------------------

invalid_item_price = order_items[
    order_items["item_price"] < 0
]

print(
    "Order items with negative item_price:",
    len(invalid_item_price)
)


# ------------------------------------------------------------
# Check order total amount
# ------------------------------------------------------------

invalid_order_amount = orders[
    orders["total_amount"] < 0
]

print(
    "Orders with negative total_amount:",
    len(invalid_order_amount)
)

Order items with quantity <= 0: 0
Order items with negative item_price: 0
Orders with negative total_amount: 0

## 2.13 Check Date and Email Quality

Dates are important for revenue trends and customer cohort analysis.

Email addresses are important for customer-level analysis.

In this step, I will inspect the date columns and identify potentially invalid email addresses.

In [15]:
# ============================================================
# STEP 2.13 - CHECK DATE AND EMAIL QUALITY
# ============================================================

# ------------------------------------------------------------
# Check sample order dates
# ------------------------------------------------------------

print("Sample Order Dates:")
display(orders["order_date"].head(10))


# ------------------------------------------------------------
# Check sample signup dates
# ------------------------------------------------------------

print("\nSample Signup Dates:")
display(users["signup_date"].head(10))


# ------------------------------------------------------------
# Check email format
# ------------------------------------------------------------

# Basic pattern:
# Something @ Something . Something

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"


# Find potentially invalid email addresses

invalid_emails = users[
    ~users["email"].astype(str).str.match(
        email_pattern,
        na=False
    )
]


# Display count

print(
    "\nPotentially invalid emails:",
    len(invalid_emails)
)


# Display a few examples

display(invalid_emails.head())

Sample Order Dates:

0    2025-09-09T14:52:37.292731
1    2025-04-15T01:18:27.193404
2    2025-04-27T15:37:48.008624
3    2025-10-04T20:35:22.204857
4    2024-11-13T08:15:18.498252
5    2024-10-13T09:02:26.848944
6    2024-05-01T04:44:56.418188
7    2024-03-03T23:33:22.844913
8    2025-10-29T07:00:11.203638
9    2024-08-13T07:04:24.298799
Name: order_date, dtype: object

Sample Signup Dates:

0    2025-03-13
1    2024-03-05
2    2025-07-07
3    2024-03-07
4    2025-01-29
5    2024-04-21
6    2024-07-03
7    2024-08-03
8    2024-06-17
9    2024-03-03
Name: signup_date, dtype: object

Potentially invalid emails: 0

Empty DataFrame
Columns: [user_id, name, email, gender, city, signup_date]
Index: []

## 2.14 Data Quality Summary

The initial exploratory analysis shows that the raw e-commerce dataset is structurally clean.

The dataset contains four related tables:
- Orders
- Order Items
- Products
- Users

The initial validation checks found no missing values, duplicate records, duplicate primary IDs, invalid foreign-key relationships, negative monetary values, or invalid email formats.

The date columns are currently stored as object/string values and will be converted to proper datetime format during the data-cleaning stage.

Since the project requires intentional inconsistencies, the next stage will create a controlled dirty copy of the raw data without modifying the original files.

In [16]:
# ============================================================
# STEP 2.14 - FINAL DATA QUALITY SUMMARY
# ============================================================

print("=" * 60)
print("INITIAL DATA QUALITY SUMMARY")
print("=" * 60)

print("\nDataset Sizes:")
print(f"Orders       : {len(orders):,} records")
print(f"Order Items  : {len(order_items):,} records")
print(f"Products     : {len(products):,} records")
print(f"Users        : {len(users):,} records")

print("\nData Quality Results:")
print("Missing values                 : 0")
print("Complete duplicate rows        : 0")
print("Duplicate primary IDs          : 0")
print("Invalid user relationships     : 0")
print("Invalid order relationships    : 0")
print("Invalid product relationships  : 0")
print("Invalid email formats          : 0")
print("Invalid quantities             : 0")
print("Negative item prices           : 0")
print("Negative order amounts         : 0")

print("\nStatus: Raw dataset passed initial quality checks.")

============================================================
INITIAL DATA QUALITY SUMMARY
============================================================

Dataset Sizes:
Orders       : 20,000 records
Order Items  : 43,525 records
Products     : 2,000 records
Users        : 10,000 records

Data Quality Results:
Missing values                 : 0
Complete duplicate rows        : 0
Duplicate primary IDs          : 0
Invalid user relationships     : 0
Invalid order relationships    : 0
Invalid product relationships  : 0
Invalid email formats          : 0
Invalid quantities             : 0
Negative item prices           : 0
Negative order amounts         : 0

Status: Raw dataset passed initial quality checks.

# 3. Create Intentional Inconsistencies in Data

The original data files successfully passed the basic tests of quality.

In order to emulate a real e-commerce system, I will create independent versions of datasets containing intentional errors.

Such errors may include:
- missing values,
- duplicates,
- incorrect foreign key references,
- wrong numeric values,
- incorrect email addresses,
- date issues.

The original data will not be changed.

In [17]:
# ============================================================
# STEP 3.1 - CREATE DIRTY COPIES
# ============================================================

# Create copies of the original DataFrames.
# We use .copy() so the original raw data is not modified.

orders_dirty = orders.copy()

order_items_dirty = order_items.copy()

products_dirty = products.copy()

users_dirty = users.copy()


# Display the shapes to confirm that the copies
# contain the same number of records.

print("Dirty Orders Shape:", orders_dirty.shape)

print("Dirty Order Items Shape:", order_items_dirty.shape)

print("Dirty Products Shape:", products_dirty.shape)

print("Dirty Users Shape:", users_dirty.shape)

Dirty Orders Shape: (20000, 5)
Dirty Order Items Shape: (43525, 7)
Dirty Products Shape: (2000, 6)
Dirty Users Shape: (10000, 6)

## 3.2 Set Random Seed

A fixed random seed makes the data corruption process reproducible.

This means that the same records will be selected every time the notebook is executed.

In [18]:
# ============================================================
# STEP 3.2 - SET RANDOM SEED
# ============================================================

# Set a fixed random seed for reproducibility.

np.random.seed(42)

print("Random seed set to 42.")

Random seed set to 42.

## 3.3 Introduce Missing Values

Real-world datasets often contain missing information.

To simulate this problem, I will intentionally introduce missing values into selected columns.

These missing values will later be handled during the data-cleaning stage.

In [19]:
# ============================================================
# STEP 3.3 - INTRODUCE MISSING VALUES
# ============================================================

# Create missing values in selected user fields.

users_dirty.loc[
    users_dirty.sample(100, random_state=42).index,
    "city"
] = np.nan


# Create missing product ratings.

products_dirty.loc[
    products_dirty.sample(50, random_state=42).index,
    "rating"
] = np.nan


# Create missing order status values.

orders_dirty.loc[
    orders_dirty.sample(50, random_state=42).index,
    "order_status"
] = np.nan


# Create missing quantities.

order_items_dirty.loc[
    order_items_dirty.sample(50, random_state=42).index,
    "quantity"
] = np.nan


print("Missing values introduced successfully.")

Missing values introduced successfully.

In [20]:
# Check the number of missing values after corruption.

print("Users missing values:")
print(users_dirty.isnull().sum())

print("\nProducts missing values:")
print(products_dirty.isnull().sum())

print("\nOrders missing values:")
print(orders_dirty.isnull().sum())

print("\nOrder Items missing values:")
print(order_items_dirty.isnull().sum())

Users missing values:
user_id          0
name             0
email            0
gender           0
city           100
signup_date      0
dtype: int64

Products missing values:
product_id       0
product_name     0
category         0
brand            0
price            0
rating          50
dtype: int64

Orders missing values:
order_id         0
user_id          0
order_date       0
order_status    50
total_amount     0
dtype: int64

Order Items missing values:
order_item_id     0
order_id          0
product_id        0
user_id           0
quantity         50
item_price        0
item_total        0
dtype: int64

## 3.4 Introduce Duplicate Records

Duplicate records can occur in real-world data because of repeated file uploads,
system errors, or repeated transactions.

To simulate this issue, I will intentionally add duplicate rows to the dirty datasets.

The original raw datasets will remain unchanged.

In [21]:
# ============================================================
# STEP 3.4 - INTRODUCE DUPLICATE RECORDS
# ============================================================

# Select 100 existing order records
# and add them again to the dirty Orders dataset.

duplicate_orders = orders_dirty.sample(
    100,
    random_state=42
)

orders_dirty = pd.concat(
    [orders_dirty, duplicate_orders],
    ignore_index=True
)


# Select 100 existing order-item records
# and add them again to the dirty Order Items dataset.

duplicate_order_items = order_items_dirty.sample(
    100,
    random_state=42
)

order_items_dirty = pd.concat(
    [order_items_dirty, duplicate_order_items],
    ignore_index=True
)


# Display the new dataset sizes

print("Orders after adding duplicates:", orders_dirty.shape)

print(
    "Order Items after adding duplicates:",
    order_items_dirty.shape
)

Orders after adding duplicates: (20100, 5)
Order Items after adding duplicates: (43625, 7)

In [22]:
# ============================================================
# VALIDATE DUPLICATE RECORDS
# ============================================================

print(
    "Duplicate Orders:",
    orders_dirty.duplicated().sum()
)

print(
    "Duplicate Order Items:",
    order_items_dirty.duplicated().sum()
)

Duplicate Orders: 100
Duplicate Order Items: 100

## 3.5 Introduce Invalid Foreign Keys

Foreign keys connect related tables.

For example:

- `orders.user_id` should exist in `users.user_id`
- `order_items.order_id` should exist in `orders.order_id`
- `order_items.product_id` should exist in `products.product_id`

To simulate real-world data quality issues, I will intentionally introduce
invalid foreign-key values into the dirty datasets.

These invalid records will later be detected during validation.

In [23]:
# ============================================================
# STEP 3.5 - INTRODUCE INVALID FOREIGN KEYS
# ============================================================

# ------------------------------------------------------------
# 1. Create invalid user IDs in orders
# ------------------------------------------------------------

# Select 50 random orders
invalid_order_rows = orders_dirty.sample(
    50,
    random_state=100
).index

# Assign user IDs that do not exist in the Users table
orders_dirty.loc[
    invalid_order_rows,
    "user_id"
] = "INVALID_USER"


# ------------------------------------------------------------
# 2. Create invalid order IDs in order_items
# ------------------------------------------------------------

invalid_item_order_rows = order_items_dirty.sample(
    50,
    random_state=101
).index

# Assign an order ID that does not exist
order_items_dirty.loc[
    invalid_item_order_rows,
    "order_id"
] = "INVALID_ORDER"


# ------------------------------------------------------------
# 3. Create invalid product IDs in order_items
# ------------------------------------------------------------

invalid_item_product_rows = order_items_dirty.sample(
    50,
    random_state=102
).index

# Assign a product ID that does not exist
order_items_dirty.loc[
    invalid_item_product_rows,
    "product_id"
] = "INVALID_PRODUCT"


print("Invalid foreign keys introduced successfully.")

Invalid foreign keys introduced successfully.

In [24]:
# ============================================================
# VALIDATE INVALID FOREIGN KEYS
# ============================================================

# Check orders -> users relationship
invalid_order_users = orders_dirty[
    ~orders_dirty["user_id"].isin(users_dirty["user_id"])
]

print(
    "Orders with invalid user_id:",
    len(invalid_order_users)
)


# Check order_items -> orders relationship
invalid_item_orders = order_items_dirty[
    ~order_items_dirty["order_id"].isin(orders_dirty["order_id"])
]

print(
    "Order items with invalid order_id:",
    len(invalid_item_orders)
)


# Check order_items -> products relationship
invalid_item_products = order_items_dirty[
    ~order_items_dirty["product_id"].isin(products_dirty["product_id"])
]

print(
    "Order items with invalid product_id:",
    len(invalid_item_products)
)

Orders with invalid user_id: 50
Order items with invalid order_id: 50
Order items with invalid product_id: 50

## 3.6 Introduce Incorrect Item Totals

The `item_total` column should follow this business rule:

item_total = quantity × item_price

To simulate incorrect transactional data, I will intentionally modify
some `item_total` values.

These incorrect values will later be detected and corrected during
the data-cleaning and validation stage.

In [25]:
# ============================================================
# STEP 3.6 - INTRODUCE INCORRECT ITEM TOTALS
# ============================================================

# Select 100 order-item records
# where quantity is not missing.

valid_quantity_rows = order_items_dirty[
    order_items_dirty["quantity"].notna()
].sample(
    100,
    random_state=200
).index


# Increase the existing item_total by 10%
# to intentionally create incorrect values.

order_items_dirty.loc[
    valid_quantity_rows,
    "item_total"
] = (
    order_items_dirty.loc[
        valid_quantity_rows,
        "item_total"
    ] * 1.10
)


print("Incorrect item_total values introduced:", len(valid_quantity_rows))

Incorrect item_total values introduced: 100

In [26]:
# ============================================================
# VALIDATE INCORRECT ITEM TOTALS
# ============================================================

# Calculate the correct item total
calculated_item_total_dirty = (
    order_items_dirty["quantity"] *
    order_items_dirty["item_price"]
)


# Compare the existing item_total with
# the calculated value.

incorrect_item_totals_dirty = order_items_dirty[
    ~np.isclose(
        order_items_dirty["item_total"],
        calculated_item_total_dirty,
        atol=0.01
    )
]


print(
    "Rows with incorrect item_total:",
    len(incorrect_item_totals_dirty)
)

Rows with incorrect item_total: 200

## 3.7 Introduce Invalid Email Addresses

Email addresses are important for customer identification and communication.

To simulate real-world data-quality issues, I will intentionally create
some invalid email formats.

Examples include:
- Missing `@`
- Missing domain
- Incorrect email structure

These records will later be detected during validation.

In [27]:
# ============================================================
# STEP 3.7 - INTRODUCE INVALID EMAILS
# ============================================================

# Select 50 users
invalid_email_rows = users_dirty.sample(
    50,
    random_state=300
).index


# Replace their emails with intentionally invalid formats.

users_dirty.loc[
    invalid_email_rows,
    "email"
] = "invalid_email"


print("Invalid email addresses introduced:", len(invalid_email_rows))

Invalid email addresses introduced: 50

In [28]:
# ============================================================
# VALIDATE INVALID EMAILS
# ============================================================

email_pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

invalid_emails_dirty = users_dirty[
    ~users_dirty["email"].astype(str).str.match(
        email_pattern,
        na=False
    )
]


print(
    "Potentially invalid emails:",
    len(invalid_emails_dirty)
)

Potentially invalid emails: 50

## 3.8 Introduce Invalid Numeric Values

In a real e-commerce system, quantities and prices should follow basic business rules.

For example:
- Quantity should be greater than 0.
- Product price should not be negative.
- Item price should not be negative.

To simulate data-quality problems, I will intentionally introduce invalid
numeric values into the dirty datasets.

In [29]:
# ============================================================
# STEP 3.8 - INTRODUCE INVALID NUMERIC VALUES
# ============================================================

# ------------------------------------------------------------
# 1. Create invalid quantities
# ------------------------------------------------------------

# Select 30 order-item records where quantity is not missing
invalid_quantity_rows = order_items_dirty[
    order_items_dirty["quantity"].notna()
].sample(
    30,
    random_state=400
).index

# Set quantity to 0
order_items_dirty.loc[
    invalid_quantity_rows,
    "quantity"
] = 0


# ------------------------------------------------------------
# 2. Create negative product prices
# ------------------------------------------------------------

invalid_product_price_rows = products_dirty.sample(
    30,
    random_state=401
).index

# Make the product prices negative
products_dirty.loc[
    invalid_product_price_rows,
    "price"
] = -abs(
    products_dirty.loc[
        invalid_product_price_rows,
        "price"
    ]
)


# ------------------------------------------------------------
# 3. Create negative item prices
# ------------------------------------------------------------

invalid_item_price_rows = order_items_dirty.sample(
    30,
    random_state=402
).index

# Make the item prices negative
order_items_dirty.loc[
    invalid_item_price_rows,
    "item_price"
] = -abs(
    order_items_dirty.loc[
        invalid_item_price_rows,
        "item_price"
    ]
)


print("Invalid numeric values introduced successfully.")

Invalid numeric values introduced successfully.

In [30]:
# ============================================================
# VALIDATE INVALID NUMERIC VALUES
# ============================================================

# Check invalid quantities
invalid_quantity_dirty = order_items_dirty[
    order_items_dirty["quantity"] <= 0
]

print(
    "Invalid quantities:",
    len(invalid_quantity_dirty)
)


# Check negative product prices
negative_product_prices = products_dirty[
    products_dirty["price"] < 0
]

print(
    "Negative product prices:",
    len(negative_product_prices)
)


# Check negative item prices
negative_item_prices = order_items_dirty[
    order_items_dirty["item_price"] < 0
]

print(
    "Negative item prices:",
    len(negative_item_prices)
)

Invalid quantities: 30
Negative product prices: 30
Negative item prices: 30

## 3.9 Introduce Date Inconsistencies

Dates are important for revenue trends, customer analysis, and cohort analysis.

An order should not normally have an order date far in the future.

To simulate a data-quality issue, I will intentionally create some future
order dates in the dirty Orders dataset.

These records will later be detected during validation.

In [39]:
# ============================================================
# STEP 3.9 - INTRODUCE FUTURE ORDER DATES
# ============================================================

# Select 30 rows from the CURRENT dirty Orders dataset
future_date_rows = orders_dirty.sample(
    n=30,
    random_state=500
).index


# Create a proper Pandas datetime value
future_date = pd.Timestamp("2030-01-01 12:00:00")


# Replace the order dates
orders_dirty.loc[
    future_date_rows,
    "order_date"
] = future_date


# Convert the COMPLETE column to datetime
orders_dirty["order_date"] = pd.to_datetime(
    orders_dirty["order_date"],
    errors="coerce"
)


# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

reference_date = pd.Timestamp("2026-08-09")

future_orders = orders_dirty[
    orders_dirty["order_date"] > reference_date
]


print("Future date values inserted:", len(future_date_rows))

print("Orders with future dates:", len(future_orders))


# Show the affected rows
display(
    orders_dirty.loc[
        future_date_rows,
        ["order_id", "order_date"]
    ].head(10)
)

Future date values inserted: 30
Orders with future dates: 30

        order_id          order_date
11459  O00011460 2030-01-01 12:00:00
14260  O00014261 2030-01-01 12:00:00
14058  O00014059 2030-01-01 12:00:00
18890  O00018891 2030-01-01 12:00:00
7912   O00007913 2030-01-01 12:00:00
3762   O00003763 2030-01-01 12:00:00
9348   O00009349 2030-01-01 12:00:00
12956  O00012957 2030-01-01 12:00:00
13935  O00013936 2030-01-01 12:00:00
12932  O00012933 2030-01-01 12:00:00

## 3.10 Save Dirty Datasets

The intentionally corrupted datasets will be saved separately from the original raw files.

This allows us to preserve the original data and use the dirty datasets as input for the data-cleaning stage.

In [40]:
# ============================================================
# STEP 3.10 - SAVE DIRTY DATASETS
# ============================================================

import os

# Create a folder for dirty datasets

dirty_folder = "data/dirty"

os.makedirs(
    dirty_folder,
    exist_ok=True
)


# ------------------------------------------------------------
# Remove the temporary validation column
# ------------------------------------------------------------

# We don't want the helper column in our CSV.

if "order_date_check" in orders_dirty.columns:
    orders_dirty = orders_dirty.drop(
        columns=["order_date_check"]
    )


# ------------------------------------------------------------
# Save all four dirty datasets
# ------------------------------------------------------------

orders_dirty.to_csv(
    f"{dirty_folder}/orders_dirty.csv",
    index=False
)

order_items_dirty.to_csv(
    f"{dirty_folder}/order_items_dirty.csv",
    index=False
)

products_dirty.to_csv(
    f"{dirty_folder}/products_dirty.csv",
    index=False
)

users_dirty.to_csv(
    f"{dirty_folder}/users_dirty.csv",
    index=False
)


print("Dirty datasets saved successfully!")
print()
print("Saved files:")

print("1. data/dirty/orders_dirty.csv")
print("2. data/dirty/order_items_dirty.csv")
print("3. data/dirty/products_dirty.csv")
print("4. data/dirty/users_dirty.csv")

Dirty datasets saved successfully!

Saved files:
1. data/dirty/orders_dirty.csv
2. data/dirty/order_items_dirty.csv
3. data/dirty/products_dirty.csv
4. data/dirty/users_dirty.csv

# 4. Data Cleaning and Validation

The dirty datasets contain intentional inconsistencies that simulate
real-world e-commerce data-quality problems.

In this section, I will use Pandas to clean, transform, and validate
the datasets before loading them into the SQL database.

In [41]:
# ============================================================
# STEP 4.1 - LOAD DIRTY DATASETS
# ============================================================

# Import Pandas
import pandas as pd


# ------------------------------------------------------------
# Load the four dirty CSV files
# ------------------------------------------------------------

orders_clean = pd.read_csv(
    "data/dirty/orders_dirty.csv"
)

order_items_clean = pd.read_csv(
    "data/dirty/order_items_dirty.csv"
)

products_clean = pd.read_csv(
    "data/dirty/products_dirty.csv"
)

users_clean = pd.read_csv(
    "data/dirty/users_dirty.csv"
)


# ------------------------------------------------------------
# Display dataset sizes
# ------------------------------------------------------------

print("Orders Shape:", orders_clean.shape)

print("Order Items Shape:", order_items_clean.shape)

print("Products Shape:", products_clean.shape)

print("Users Shape:", users_clean.shape)

Orders Shape: (20100, 5)
Order Items Shape: (43625, 7)
Products Shape: (2000, 6)
Users Shape: (10000, 6)

## 4.2 Check Data Types

Correct data types are important for reliable analysis.

For example:
- Dates should be stored as datetime.
- Quantities should be numeric.
- Prices and amounts should be numeric.
- IDs should be treated consistently across related tables.

In [42]:
# ============================================================
# STEP 4.2 - CHECK DATA TYPES
# ============================================================

print("ORDERS DATA TYPES")
print(orders_clean.dtypes)

print("\nORDER ITEMS DATA TYPES")
print(order_items_clean.dtypes)

print("\nPRODUCTS DATA TYPES")
print(products_clean.dtypes)

print("\nUSERS DATA TYPES")
print(users_clean.dtypes)

ORDERS DATA TYPES
order_id         object
user_id          object
order_date       object
order_status     object
total_amount    float64
dtype: object

ORDER ITEMS DATA TYPES
order_item_id     object
order_id          object
product_id        object
user_id           object
quantity         float64
item_price       float64
item_total       float64
dtype: object

PRODUCTS DATA TYPES
product_id       object
product_name     object
category         object
brand            object
price           float64
rating          float64
dtype: object

USERS DATA TYPES
user_id        object
name           object
email          object
gender         object
city           object
signup_date    object
dtype: object

## 4.3 Convert Date Columns

The order date and signup date are currently stored as text.

I will convert them into Pandas datetime format so that we can:
- compare dates,
- identify future dates,
- calculate time differences,
- perform monthly and yearly analysis.

In [43]:
# ============================================================
# STEP 4.3 - CONVERT DATE COLUMNS
# ============================================================

# Convert order_date into datetime format
orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"],
    errors="coerce"
)

# Convert signup_date into datetime format
users_clean["signup_date"] = pd.to_datetime(
    users_clean["signup_date"],
    errors="coerce"
)


# ------------------------------------------------------------
# Check the results
# ------------------------------------------------------------

print("Order date type:")
print(orders_clean["order_date"].dtype)

print("\nSignup date type:")
print(users_clean["signup_date"].dtype)

Order date type:
datetime64[ns]

Signup date type:
datetime64[ns]

## 4.4 Handle Missing Values

Missing values can affect calculations and SQL analysis.

Instead of blindly deleting records, appropriate values are used based
on the meaning of each column.

- Missing city → "Unknown"
- Missing product rating → median rating
- Missing order status → "Unknown"
- Missing quantity → median quantity

In [44]:
# ============================================================
# STEP 4.4 - HANDLE MISSING VALUES
# ============================================================


# ------------------------------------------------------------
# USERS
# ------------------------------------------------------------

# Replace missing city values with "Unknown"

users_clean["city"] = users_clean["city"].fillna(
    "Unknown"
)


# ------------------------------------------------------------
# PRODUCTS
# ------------------------------------------------------------

# Replace missing ratings with the median rating

product_rating_median = products_clean["rating"].median()

products_clean["rating"] = products_clean["rating"].fillna(
    product_rating_median
)


# ------------------------------------------------------------
# ORDERS
# ------------------------------------------------------------

# Replace missing order status

orders_clean["order_status"] = orders_clean["order_status"].fillna(
    "Unknown"
)


# ------------------------------------------------------------
# ORDER ITEMS
# ------------------------------------------------------------

# Replace missing quantity with median quantity

quantity_median = order_items_clean["quantity"].median()

order_items_clean["quantity"] = order_items_clean["quantity"].fillna(
    quantity_median
)


# ------------------------------------------------------------
# CHECK MISSING VALUES AGAIN
# ------------------------------------------------------------

print("Remaining missing values:")

print("\nUsers:")
print(users_clean.isnull().sum())

print("\nProducts:")
print(products_clean.isnull().sum())

print("\nOrders:")
print(orders_clean.isnull().sum())

print("\nOrder Items:")
print(order_items_clean.isnull().sum())

Remaining missing values:

Users:
user_id        0
name           0
email          0
gender         0
city           0
signup_date    0
dtype: int64

Products:
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

Orders:
order_id        0
user_id         0
order_date      0
order_status    0
total_amount    0
dtype: int64

Order Items:
order_item_id    0
order_id         0
product_id       0
user_id          0
quantity         0
item_price       0
item_total       0
dtype: int64

## 4.5 Remove Duplicate Records

Duplicate records can cause incorrect revenue, order counts, and customer
metrics.

In this step, duplicate rows are identified and removed from the Orders
and Order Items datasets.

The original datasets contained 100 intentionally duplicated rows in
each of these tables.

In [45]:
# ============================================================
# STEP 4.5 - REMOVE DUPLICATE RECORDS
# ============================================================

# ------------------------------------------------------------
# Check duplicates BEFORE cleaning
# ------------------------------------------------------------

print("Duplicate Orders BEFORE cleaning:",
      orders_clean.duplicated().sum())

print("Duplicate Order Items BEFORE cleaning:",
      order_items_clean.duplicated().sum())


# ------------------------------------------------------------
# Remove complete duplicate rows
# keep="first" keeps the original record and removes
# subsequent copies.
# ------------------------------------------------------------

orders_clean = orders_clean.drop_duplicates(
    keep="first"
).reset_index(drop=True)


order_items_clean = order_items_clean.drop_duplicates(
    keep="first"
).reset_index(drop=True)


# ------------------------------------------------------------
# Check duplicates AFTER cleaning
# ------------------------------------------------------------

print("\nDuplicate Orders AFTER cleaning:",
      orders_clean.duplicated().sum())

print("Duplicate Order Items AFTER cleaning:",
      order_items_clean.duplicated().sum())


# ------------------------------------------------------------
# Display updated dataset sizes
# ------------------------------------------------------------

print("\nUpdated Dataset Sizes:")

print("Orders:", orders_clean.shape)

print("Order Items:", order_items_clean.shape)

Duplicate Orders BEFORE cleaning: 99
Duplicate Order Items BEFORE cleaning: 100

Duplicate Orders AFTER cleaning: 0
Duplicate Order Items AFTER cleaning: 0

Updated Dataset Sizes:
Orders: (20001, 5)
Order Items: (43525, 7)

## 4.6 Fix Invalid Foreign Key Relationships

Foreign keys connect the different tables in the e-commerce database.

Invalid foreign keys can cause incorrect joins and missing records during
SQL analysis.

In this step, invalid relationships are identified and removed.

In [46]:
# ============================================================
# STEP 4.6 - VALIDATE AND FIX FOREIGN KEYS
# ============================================================

# ------------------------------------------------------------
# Create sets containing valid IDs
# ------------------------------------------------------------

valid_user_ids = set(users_clean["user_id"])

valid_order_ids = set(orders_clean["order_id"])

valid_product_ids = set(products_clean["product_id"])


# ------------------------------------------------------------
# Find invalid user IDs in Orders
# ------------------------------------------------------------

invalid_orders = orders_clean[
    ~orders_clean["user_id"].isin(valid_user_ids)
]

print(
    "Invalid user_id records in Orders:",
    len(invalid_orders)
)


# ------------------------------------------------------------
# Find invalid order IDs in Order Items
# ------------------------------------------------------------

invalid_order_items = order_items_clean[
    ~order_items_clean["order_id"].isin(valid_order_ids)
]

print(
    "Invalid order_id records in Order Items:",
    len(invalid_order_items)
)


# ------------------------------------------------------------
# Find invalid product IDs in Order Items
# ------------------------------------------------------------

invalid_product_items = order_items_clean[
    ~order_items_clean["product_id"].isin(valid_product_ids)
]

print(
    "Invalid product_id records in Order Items:",
    len(invalid_product_items)
)


# ------------------------------------------------------------
# Remove invalid relationships
# ------------------------------------------------------------

orders_clean = orders_clean[
    orders_clean["user_id"].isin(valid_user_ids)
].reset_index(drop=True)


order_items_clean = order_items_clean[
    order_items_clean["order_id"].isin(valid_order_ids)
].reset_index(drop=True)


order_items_clean = order_items_clean[
    order_items_clean["product_id"].isin(valid_product_ids)
].reset_index(drop=True)


# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

print("\nAfter cleaning:")

print(
    "Invalid user_id records:",
    len(
        orders_clean[
            ~orders_clean["user_id"].isin(valid_user_ids)
        ]
    )
)

print(
    "Invalid order_id records:",
    len(
        order_items_clean[
            ~order_items_clean["order_id"].isin(valid_order_ids)
        ]
    )
)

print(
    "Invalid product_id records:",
    len(
        order_items_clean[
            ~order_items_clean["product_id"].isin(valid_product_ids)
        ]
    )
)

Invalid user_id records in Orders: 50
Invalid order_id records in Order Items: 50
Invalid product_id records in Order Items: 50

After cleaning:
Invalid user_id records: 0
Invalid order_id records: 0
Invalid product_id records: 0

## 4.7 Fix Invalid Numeric Values

Numeric fields such as quantity and price must contain valid business
values.

For an e-commerce system:

- Quantity must be greater than 0.
- Item price cannot be negative.
- Product price cannot be negative.

Invalid values will be replaced using the median of valid values.

In [47]:
# ============================================================
# STEP 4.7 - FIX INVALID NUMERIC VALUES
# ============================================================

# ------------------------------------------------------------
# 1. Fix invalid quantity
# ------------------------------------------------------------

# Identify valid quantities
valid_quantities = order_items_clean[
    order_items_clean["quantity"] > 0
]["quantity"]

# Calculate median of valid quantities
quantity_median = valid_quantities.median()

# Replace quantity <= 0 with median
order_items_clean.loc[
    order_items_clean["quantity"] <= 0,
    "quantity"
] = quantity_median


# ------------------------------------------------------------
# 2. Fix negative item prices
# ------------------------------------------------------------

# Identify valid item prices
valid_item_prices = order_items_clean[
    order_items_clean["item_price"] >= 0
]["item_price"]

# Calculate median valid price
item_price_median = valid_item_prices.median()

# Replace negative prices
order_items_clean.loc[
    order_items_clean["item_price"] < 0,
    "item_price"
] = item_price_median


# ------------------------------------------------------------
# 3. Fix negative product prices
# ------------------------------------------------------------

# Identify valid product prices
valid_product_prices = products_clean[
    products_clean["price"] >= 0
]["price"]

# Calculate median valid product price
product_price_median = valid_product_prices.median()

# Replace negative prices
products_clean.loc[
    products_clean["price"] < 0,
    "price"
] = product_price_median


# ------------------------------------------------------------
# VALIDATION
# ------------------------------------------------------------

print(
    "Invalid quantities remaining:",
    (order_items_clean["quantity"] <= 0).sum()
)

print(
    "Negative item prices remaining:",
    (order_items_clean["item_price"] < 0).sum()
)

print(
    "Negative product prices remaining:",
    (products_clean["price"] < 0).sum()
)

Invalid quantities remaining: 0
Negative item prices remaining: 0
Negative product prices remaining: 0

## 4.8 Recalculate Item Total

The `item_total` column may contain incorrect values due to data-entry
or processing errors.

The correct item total is calculated using:

item_total = quantity × item_price

Recalculating this field ensures consistency between quantity, price,
and total amount.

In [48]:
# ============================================================
# STEP 4.8 - RECALCULATE ITEM TOTAL
# ============================================================

# Calculate the correct item total
order_items_clean["calculated_item_total"] = (
    order_items_clean["quantity"]
    * order_items_clean["item_price"]
)


# ------------------------------------------------------------
# Find records where the existing total is incorrect
# ------------------------------------------------------------

incorrect_item_totals = order_items_clean[
    ~np.isclose(
        order_items_clean["item_total"],
        order_items_clean["calculated_item_total"],
        rtol=1e-05,
        atol=0.01
    )
]


print(
    "Incorrect item_total records found:",
    len(incorrect_item_totals)
)


# ------------------------------------------------------------
# Replace incorrect totals with calculated totals
# ------------------------------------------------------------

order_items_clean["item_total"] = (
    order_items_clean["calculated_item_total"]
)


# ------------------------------------------------------------
# Remove temporary calculation column
# ------------------------------------------------------------

order_items_clean = order_items_clean.drop(
    columns=["calculated_item_total"]
)


# ------------------------------------------------------------
# Final validation
# ------------------------------------------------------------

validation_check = np.isclose(
    order_items_clean["item_total"],
    order_items_clean["quantity"]
    * order_items_clean["item_price"],
    rtol=1e-05,
    atol=0.01
)


print(
    "Incorrect item_total records remaining:",
    (~validation_check).sum()
)

Incorrect item_total records found: 156
Incorrect item_total records remaining: 0

## 4.9 Fix Invalid Email Formats

Email addresses are important for identifying and contacting customers.

In this step, invalid email formats are identified using a regular
expression.

Invalid emails will be replaced with a valid placeholder email based
on the user's ID.

In [49]:
# ============================================================
# STEP 4.9 - FIX INVALID EMAIL FORMATS
# ============================================================

import re


# ------------------------------------------------------------
# Define a simple email validation pattern
# ------------------------------------------------------------

email_pattern = r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$"


# ------------------------------------------------------------
# Identify invalid emails
# ------------------------------------------------------------

valid_email_mask = users_clean["email"].astype(str).str.match(
    email_pattern,
    na=False
)


invalid_email_count = (~valid_email_mask).sum()

print(
    "Invalid email records found:",
    invalid_email_count
)


# ------------------------------------------------------------
# Replace invalid emails
# ------------------------------------------------------------

users_clean.loc[
    ~valid_email_mask,
    "email"
] = (
    "user_"
    + users_clean.loc[~valid_email_mask, "user_id"].astype(str)
    + "@example.com"
)


# ------------------------------------------------------------
# Validate emails again
# ------------------------------------------------------------

remaining_invalid_emails = ~users_clean[
    "email"
].astype(str).str.match(
    email_pattern,
    na=False
)


print(
    "Invalid email records remaining:",
    remaining_invalid_emails.sum()
)

Invalid email records found: 50
Invalid email records remaining: 0

## 4.10 Fix Future Order Dates

Order dates should not be later than the reference date of the analysis.

The dataset contains intentionally inserted future dates. These records
will be corrected by replacing future dates with the median valid
historical order date.

This preserves the transaction records while maintaining date integrity.

In [50]:
# ============================================================
# STEP 4.10 - FIX FUTURE ORDER DATES
# ============================================================

# Reference date for validation
reference_date = pd.Timestamp("2026-08-09")


# ------------------------------------------------------------
# Find future order dates
# ------------------------------------------------------------

future_date_mask = (
    orders_clean["order_date"] > reference_date
)

print(
    "Future order dates found:",
    future_date_mask.sum()
)


# ------------------------------------------------------------
# Calculate median of valid historical dates
# ------------------------------------------------------------

valid_order_dates = orders_clean.loc[
    ~future_date_mask,
    "order_date"
]

median_order_date = valid_order_dates.sort_values().iloc[
    len(valid_order_dates) // 2
]


print(
    "Replacement date:",
    median_order_date
)


# ------------------------------------------------------------
# Replace future dates
# ------------------------------------------------------------

orders_clean.loc[
    future_date_mask,
    "order_date"
] = median_order_date


# ------------------------------------------------------------
# Validate again
# ------------------------------------------------------------

remaining_future_dates = (
    orders_clean["order_date"] > reference_date
).sum()


print(
    "Future order dates remaining:",
    remaining_future_dates
)

Future order dates found: 30
Replacement date: 2024-12-05 07:11:48.486155
Future order dates remaining: 0

## 4.11 Final Data Quality Validation

After cleaning the datasets, a final validation is performed to ensure
that the major data-quality issues have been resolved.

The final checks include missing values, duplicates, invalid
relationships, invalid numeric values, incorrect item totals, invalid
emails, and future dates.

In [51]:
# ============================================================
# STEP 4.11 - FINAL DATA QUALITY VALIDATION
# ============================================================


print("=" * 60)
print("FINAL DATA QUALITY VALIDATION")
print("=" * 60)


# ------------------------------------------------------------
# 1. Missing values
# ------------------------------------------------------------

print("\n1. MISSING VALUES")

print("Users:",
      users_clean.isnull().sum().sum())

print("Products:",
      products_clean.isnull().sum().sum())

print("Orders:",
      orders_clean.isnull().sum().sum())

print("Order Items:",
      order_items_clean.isnull().sum().sum())


# ------------------------------------------------------------
# 2. Duplicate rows
# ------------------------------------------------------------

print("\n2. DUPLICATE ROWS")

print("Orders:",
      orders_clean.duplicated().sum())

print("Order Items:",
      order_items_clean.duplicated().sum())

print("Products:",
      products_clean.duplicated().sum())

print("Users:",
      users_clean.duplicated().sum())


# ------------------------------------------------------------
# 3. Invalid foreign keys
# ------------------------------------------------------------

valid_user_ids = set(users_clean["user_id"])
valid_order_ids = set(orders_clean["order_id"])
valid_product_ids = set(products_clean["product_id"])


invalid_user_fk = (
    ~orders_clean["user_id"].isin(valid_user_ids)
).sum()

invalid_order_fk = (
    ~order_items_clean["order_id"].isin(valid_order_ids)
).sum()

invalid_product_fk = (
    ~order_items_clean["product_id"].isin(valid_product_ids)
).sum()


print("\n3. INVALID FOREIGN KEYS")

print("Orders → Users:",
      invalid_user_fk)

print("Order Items → Orders:",
      invalid_order_fk)

print("Order Items → Products:",
      invalid_product_fk)


# ------------------------------------------------------------
# 4. Invalid numeric values
# ------------------------------------------------------------

print("\n4. INVALID NUMERIC VALUES")

print(
    "Invalid quantities:",
    (order_items_clean["quantity"] <= 0).sum()
)

print(
    "Negative item prices:",
    (order_items_clean["item_price"] < 0).sum()
)

print(
    "Negative product prices:",
    (products_clean["price"] < 0).sum()
)


# ------------------------------------------------------------
# 5. Incorrect item totals
# ------------------------------------------------------------

correct_totals = np.isclose(
    order_items_clean["item_total"],
    order_items_clean["quantity"]
    * order_items_clean["item_price"],
    rtol=1e-05,
    atol=0.01
)


print("\n5. INCORRECT ITEM TOTALS")

print(
    "Incorrect item totals:",
    (~correct_totals).sum()
)


# ------------------------------------------------------------
# 6. Invalid emails
# ------------------------------------------------------------

invalid_emails = ~users_clean["email"].astype(str).str.match(
    email_pattern,
    na=False
)


print("\n6. INVALID EMAILS")

print(
    "Invalid emails:",
    invalid_emails.sum()
)


# ------------------------------------------------------------
# 7. Future order dates
# ------------------------------------------------------------

future_dates = (
    orders_clean["order_date"] > reference_date
).sum()


print("\n7. FUTURE ORDER DATES")

print(
    "Future order dates:",
    future_dates
)


print("\n" + "=" * 60)
print("FINAL VALIDATION COMPLETED")
print("=" * 60)

============================================================
FINAL DATA QUALITY VALIDATION
============================================================

1. MISSING VALUES
Users: 0
Products: 0
Orders: 0
Order Items: 0

2. DUPLICATE ROWS
Orders: 0
Order Items: 0
Products: 0
Users: 0

3. INVALID FOREIGN KEYS
Orders → Users: 0
Order Items → Orders: 109
Order Items → Products: 0

4. INVALID NUMERIC VALUES
Invalid quantities: 0
Negative item prices: 0
Negative product prices: 0

5. INCORRECT ITEM TOTALS
Incorrect item totals: 0

6. INVALID EMAILS
Invalid emails: 0

7. FUTURE ORDER DATES
Future order dates: 0

============================================================
FINAL VALIDATION COMPLETED
============================================================

# 5. Save Clean Datasets

After completing the data-cleaning and validation process, the cleaned
datasets are saved separately.

These clean datasets will be used for SQL-based analysis and reporting.

In [52]:
# ============================================================
# STEP 5 - SAVE CLEAN DATASETS
# ============================================================

import os

# Create clean data folder
clean_folder = "data/clean"

os.makedirs(
    clean_folder,
    exist_ok=True
)


# ------------------------------------------------------------
# Save cleaned datasets
# ------------------------------------------------------------

orders_clean.to_csv(
    f"{clean_folder}/orders_clean.csv",
    index=False
)

order_items_clean.to_csv(
    f"{clean_folder}/order_items_clean.csv",
    index=False
)

products_clean.to_csv(
    f"{clean_folder}/products_clean.csv",
    index=False
)

users_clean.to_csv(
    f"{clean_folder}/users_clean.csv",
    index=False
)


# ------------------------------------------------------------
# Confirmation
# ------------------------------------------------------------

print("Clean datasets saved successfully!")

print("\nSaved files:")

print("1. data/clean/orders_clean.csv")
print("2. data/clean/order_items_clean.csv")
print("3. data/clean/products_clean.csv")
print("4. data/clean/users_clean.csv")

Clean datasets saved successfully!

Saved files:
1. data/clean/orders_clean.csv
2. data/clean/order_items_clean.csv
3. data/clean/products_clean.csv
4. data/clean/users_clean.csv

# 6. SQL Database Setup

The cleaned e-commerce datasets will be loaded into a SQLite database.

Four relational tables will be created:

1. users
2. products
3. orders
4. order_items

These tables will be connected using primary and foreign-key relationships.

In [53]:
# ============================================================
# STEP 6.1 - CREATE SQLITE DATABASE CONNECTION
# ============================================================

import sqlite3

# Create / connect to SQLite database
connection = sqlite3.connect(
    "ecommerce.db"
)

print("SQLite database connected successfully!")

SQLite database connected successfully!

## 6.2 Load Clean Data into SQL Tables

The cleaned Pandas DataFrames will be loaded into SQLite tables.

The table names will match the original dataset names so that the SQL
queries remain easy to understand.

In [54]:
# ============================================================
# STEP 6.2 - LOAD DATA INTO SQLITE
# ============================================================

# Load Users table
users_clean.to_sql(
    "users",
    connection,
    if_exists="replace",
    index=False
)


# Load Products table
products_clean.to_sql(
    "products",
    connection,
    if_exists="replace",
    index=False
)


# Load Orders table
orders_clean.to_sql(
    "orders",
    connection,
    if_exists="replace",
    index=False
)


# Load Order Items table
order_items_clean.to_sql(
    "order_items",
    connection,
    if_exists="replace",
    index=False
)


print("All four tables loaded successfully!")

All four tables loaded successfully!

In [55]:
# ============================================================
# STEP 6.3 - VERIFY SQL TABLES
# ============================================================

tables = pd.read_sql_query(
    """
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
    """,
    connection
)

display(tables)

          name
0  order_items
1       orders
2     products
3        users

In [56]:
# ============================================================
# STEP 6.4 - CHECK TABLE ROW COUNTS
# ============================================================

queries = {
    "Users": "SELECT COUNT(*) AS total_records FROM users;",
    "Products": "SELECT COUNT(*) AS total_records FROM products;",
    "Orders": "SELECT COUNT(*) AS total_records FROM orders;",
    "Order Items": "SELECT COUNT(*) AS total_records FROM order_items;"
}


for table_name, query in queries.items():

    result = pd.read_sql_query(
        query,
        connection
    )

    print(
        f"{table_name}:",
        result.iloc[0]["total_records"]
    )

Users: 10000
Products: 2000
Orders: 19951
Order Items: 43425

# 7. SQL Analysis — JOINs and Aggregations

In this section, SQL JOINs and aggregate functions are used to generate
customer-level business insights.

We will calculate:

- Number of orders per customer
- Total quantity purchased
- Total amount spent
- Average order value

In [57]:
# ============================================================
# STEP 7.1 - CUSTOMER PURCHASE SUMMARY
# ============================================================

customer_summary = pd.read_sql_query(
    """
    SELECT
        u.user_id,
        u.name,
        u.city,

        -- Count the number of orders made by each customer
        COUNT(DISTINCT o.order_id) AS total_orders,

        -- Total number of products purchased
        SUM(oi.quantity) AS total_quantity,

        -- Total money spent by the customer
        SUM(oi.item_total) AS total_spent,

        -- Average amount spent per order
        ROUND(
            SUM(oi.item_total) / COUNT(DISTINCT o.order_id),
            2
        ) AS average_order_value

    FROM users AS u

    -- Connect customers with their orders
    INNER JOIN orders AS o
        ON u.user_id = o.user_id

    -- Connect orders with individual products
    INNER JOIN order_items AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        u.user_id,
        u.name,
        u.city

    ORDER BY
        total_spent DESC;
    """,
    connection
)

display(customer_summary.head(10))

,user_id,name,city,total_orders,total_quantity,total_spent,average_order_value
0,U009931,Meagan Case,Unknown,4,16.00,13288.88,3322.22
1,U006233,Willie Esparza,Tylerland,3,20.00,11234.22,3744.74
2,U006469,Audrey Ware,South Robertstad,4,28.00,10953.18,2738.30
3,U008370,Brittany Carrillo,Bryanport,2,13.00,10190.11,5095.06
4,U005702,Shawn Greene,New Ashleebury,6,25.00,10175.81,1695.97
5,U009903,Jessica Russell,Nolanborough,5,26.00,10118.31,2023.66
6,U000006,Michael Santiago,East Steven,6,19.00,9952.28,1658.71
7,U004906,Brenda Winters,East Emilyview,5,26.00,9538.69,1907.74
8,U006231,Jerome Warner,Port Katherineview,2,14.00,9486.29,4743.15
9,U007930,Robert Jennings,Port James,9,25.00,8947.98,994.22

## 7.2 Product and Category Revenue Analysis

This analysis identifies the best-performing product categories.

We calculate:

- Number of products sold
- Total quantity sold
- Total revenue
- Average product price
- Average product rating

This helps the business understand which categories contribute the most revenue.

In [58]:
# ============================================================
# STEP 7.2 - PRODUCT CATEGORY REVENUE ANALYSIS
# ============================================================

category_summary = pd.read_sql_query(
    """
    SELECT
        p.category,

        -- Number of different products in the category
        COUNT(DISTINCT p.product_id) AS total_products,

        -- Total quantity sold
        SUM(oi.quantity) AS total_quantity_sold,

        -- Total revenue generated
        ROUND(SUM(oi.item_total), 2) AS total_revenue,

        -- Average product price
        ROUND(AVG(p.price), 2) AS average_product_price,

        -- Average product rating
        ROUND(AVG(p.rating), 2) AS average_rating

    FROM products AS p

    -- Connect products with order items
    INNER JOIN order_items AS oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.category

    ORDER BY
        total_revenue DESC;
    """,
    connection
)

display(category_summary)

,category,total_products,total_quantity_sold,total_revenue,average_product_price,average_rating
0,Electronics,203,5863.00,4936846.91,839.88,3.70
1,Automotive,193,5903.00,2492784.13,413.12,3.60
2,Home & Kitchen,199,5884.00,1128015.62,187.18,3.68
3,Sports,183,5628.00,947578.60,167.58,3.69
4,Clothing,213,6397.00,709667.75,110.46,3.71
5,Beauty,207,6312.00,554148.60,87.67,3.61
6,Toys,213,6503.00,384283.54,59.43,3.69
7,Pet Supplies,212,6696.00,353044.10,52.76,3.66
8,Books,194,6050.00,273913.53,45.55,3.71
9,Groceries,183,5409.00,89653.41,16.81,3.66

## 7.3 Monthly Revenue Trend

Monthly revenue is calculated using order dates.

This helps identify:

- High-revenue months
- Low-revenue months
- Overall sales trends

In [59]:
# ============================================================
# STEP 7.3 - MONTHLY REVENUE TREND
# ============================================================

monthly_revenue = pd.read_sql_query(
    """
    SELECT
        strftime('%Y-%m', o.order_date) AS order_month,

        COUNT(DISTINCT o.order_id) AS total_orders,

        SUM(oi.quantity) AS total_quantity_sold,

        ROUND(SUM(oi.item_total), 2) AS total_revenue

    FROM orders AS o

    INNER JOIN order_items AS oi
        ON o.order_id = oi.order_id

    GROUP BY
        order_month

    ORDER BY
        order_month;
    """,
    connection
)

display(monthly_revenue)

   order_month  total_orders  total_quantity_sold  total_revenue
0      2024-01           880              2653.00      542175.45
1      2024-02           807              2505.00      502933.09
2      2024-03           949              2818.00      537780.48
3      2024-04           923              2853.00      539439.56
4      2024-05           900              2724.00      545178.65
5      2024-06           895              2699.00      546121.51
6      2024-07           952              2910.00      583345.16
7      2024-08           879              2659.00      516802.40
8      2024-09           881              2627.00      524160.08
9      2024-10           895              2708.00      527608.85
10     2024-11           873              2600.00      510188.82
11     2024-12           914              2842.00      579209.81
12     2025-01           882              2697.00      502234.50
13     2025-02           821              2476.00      457861.84
14     2025-03           879              2739.00      501326.48
15     2025-04           855              2637.00      521815.24
16     2025-05           902              2670.00      536590.38
17     2025-06           858              2585.00      501536.08
18     2025-07           896              2710.00      545911.08
19     2025-08           917              2699.00      506375.11
20     2025-09           892              2721.00      516293.23
21     2025-10           888              2716.00      516542.43
22     2025-11           388              1234.00      276873.72

# 8. SQL Window Functions

Window functions allow us to perform calculations across related rows
without grouping the rows into a single result.

In this section, we rank customers within each city based on their
total spending.

This helps identify the highest-value customers in different cities.

In [60]:
# ============================================================
# STEP 8.1 - RANK CUSTOMERS WITH WINDOW FUNCTION
# ============================================================

top_customers_by_city = pd.read_sql_query(
    """

    -- First calculate total spending for every customer
    WITH customer_spending AS (

        SELECT
            u.user_id,
            u.name,
            u.city,

            -- Calculate total money spent
            ROUND(SUM(oi.item_total), 2) AS total_spent

        FROM users AS u

        -- Connect users to orders
        INNER JOIN orders AS o
            ON u.user_id = o.user_id

        -- Connect orders to order items
        INNER JOIN order_items AS oi
            ON o.order_id = oi.order_id

        GROUP BY
            u.user_id,
            u.name,
            u.city
    )


    -- Rank customers inside each city
    SELECT
        user_id,
        name,
        city,
        total_spent,

        RANK() OVER (
            PARTITION BY city
            ORDER BY total_spent DESC
        ) AS city_rank

    FROM customer_spending

    ORDER BY
        city,
        city_rank;

    """,
    connection
)

display(top_customers_by_city.head(20))

    user_id                name         city  total_spent  city_rank
0   U004431       Lisa Robinson    Aaronberg      3726.86          1
1   U004526       Connie Brandt    Aaronbury       598.87          1
2   U006800        Martin Smith    Aaronside       737.64          1
3   U002442      Michele Vargas     Aaronton      1421.25          1
4   U002348      Patricia Smith  Abigailstad        26.54          1
5   U002669     Jennifer Acosta  Abigailtown       716.74          1
6   U008110          Ryan Curry  Abigailview      2071.97          1
7   U006154         Mary Joseph  Acevedoside       955.71          1
8   U003668        Jason Fowler  Adamborough      2641.77          1
9   U001201  Kimberly Stevenson     Adamfurt      2769.43          1
10  U003844        Alan Estrada     Adamfurt       892.44          2
11  U007613     Norman Chambers    Adamsland      2132.97          1
12  U007766         Ronald Pham   Adamsmouth      1898.26          1
13  U002913      George Santana   Adamsmouth       257.39          2
14  U008742      Bryan Fletcher   Adamsshire      2838.16          1
15  U003943         Megan Logan      Adamton      7630.24          1
16  U008926         Ryan Howell     Adamview       736.89          1
17  U008586      Kimberly Smith    Adamville       401.63          1
18  U009935      Nathan Simmons   Adkinsstad      3005.22          1
19  U003871     Matthew Sanchez    Adkinston       378.66          1

## 8.2 Top 3 Customers in Each City

The ranking generated by the window function is used to identify
the three highest-spending customers from every city.

In [61]:
# ============================================================
# STEP 8.2 - TOP 3 CUSTOMERS PER CITY
# ============================================================

top_3_customers = top_customers_by_city[
    top_customers_by_city["city_rank"] <= 3
].copy()

display(
    top_3_customers.head(30)
)

    user_id                name           city  total_spent  city_rank
0   U004431       Lisa Robinson      Aaronberg      3726.86          1
1   U004526       Connie Brandt      Aaronbury       598.87          1
2   U006800        Martin Smith      Aaronside       737.64          1
3   U002442      Michele Vargas       Aaronton      1421.25          1
4   U002348      Patricia Smith    Abigailstad        26.54          1
5   U002669     Jennifer Acosta    Abigailtown       716.74          1
6   U008110          Ryan Curry    Abigailview      2071.97          1
7   U006154         Mary Joseph    Acevedoside       955.71          1
8   U003668        Jason Fowler    Adamborough      2641.77          1
9   U001201  Kimberly Stevenson       Adamfurt      2769.43          1
10  U003844        Alan Estrada       Adamfurt       892.44          2
11  U007613     Norman Chambers      Adamsland      2132.97          1
12  U007766         Ronald Pham     Adamsmouth      1898.26          1
13  U002913      George Santana     Adamsmouth       257.39          2
14  U008742      Bryan Fletcher     Adamsshire      2838.16          1
15  U003943         Megan Logan        Adamton      7630.24          1
16  U008926         Ryan Howell       Adamview       736.89          1
17  U008586      Kimberly Smith      Adamville       401.63          1
18  U009935      Nathan Simmons     Adkinsstad      3005.22          1
19  U003871     Matthew Sanchez      Adkinston       378.66          1
20  U009206          Juan Hayes   Adrianaville      2129.21          1
21  U003809      Jennifer Garza    Adrianmouth      1917.91          1
22  U004357    Adriana Anderson    Adrianville       986.61          1
23  U009755   Patricia Thompson    Aguilarfort       172.42          1
24  U009290      Jennifer Joyce    Aguirreland      2031.02          1
25  U001870      Stephen Palmer     Aguirreton       300.82          1
26  U002850   Jeffrey Henderson  Albertborough      2269.12          1
27  U007172    Christina Hansen     Albertland       363.03          1
28  U003695        Barbara Mann     Albertport      1670.08          1
29  U005494       Andrew Walker     Albertside      1159.84          1

# 9. Customer Segmentation Using CTE

Customers are segmented according to their total spending.

Segments:

- High Value: Total spending >= 5000
- Medium Value: Total spending between 2000 and 4999.99
- Low Value: Total spending < 2000

A Common Table Expression (CTE) is used to first calculate customer
spending and then classify customers into segments.

In [62]:
# ============================================================
# STEP 9.1 - CUSTOMER SEGMENTATION USING CTE
# ============================================================

customer_segments = pd.read_sql_query(
    """

    -- ========================================================
    -- CTE: Calculate total spending for each customer
    -- ========================================================

    WITH customer_spending AS (

        SELECT
            u.user_id,
            u.name,
            u.city,

            -- Total amount spent by the customer
            ROUND(SUM(oi.item_total), 2) AS total_spent,

            -- Number of orders made by the customer
            COUNT(DISTINCT o.order_id) AS total_orders

        FROM users AS u

        INNER JOIN orders AS o
            ON u.user_id = o.user_id

        INNER JOIN order_items AS oi
            ON o.order_id = oi.order_id

        GROUP BY
            u.user_id,
            u.name,
            u.city
    )


    -- ========================================================
    -- Segment customers based on total spending
    -- ========================================================

    SELECT
        user_id,
        name,
        city,
        total_orders,
        total_spent,

        CASE

            -- Customers spending 5000 or more
            WHEN total_spent >= 5000
                THEN 'High Value'

            -- Customers spending between 2000 and 4999.99
            WHEN total_spent >= 2000
                THEN 'Medium Value'

            -- Customers spending less than 2000
            ELSE 'Low Value'

        END AS customer_segment

    FROM customer_spending

    ORDER BY
        total_spent DESC;

    """,
    connection
)

display(customer_segments.head(20))

,user_id,name,city,total_orders,total_spent,customer_segment
0,U009931,Meagan Case,Unknown,4,13288.88,High Value
1,U006233,Willie Esparza,Tylerland,3,11234.22,High Value
2,U006469,Audrey Ware,South Robertstad,4,10953.18,High Value
3,U008370,Brittany Carrillo,Bryanport,2,10190.11,High Value
4,U005702,Shawn Greene,New Ashleebury,6,10175.81,High Value
5,U009903,Jessica Russell,Nolanborough,5,10118.31,High Value
6,U000006,Michael Santiago,East Steven,6,9952.28,High Value
7,U004906,Brenda Winters,East Emilyview,5,9538.69,High Value
8,U006231,Jerome Warner,Port Katherineview,2,9486.29,High Value
9,U007930,Robert Jennings,Port James,9,8947.98,High Value
10,U005279,Joseph Houston,Luistown,4,8906.97,High Value
11,U009674,Julia Myers,Lake Stephen,5,8789.92,High Value
12,U000567,Gregory Vasquez,South Jenniferville,3,8753.35,High Value
13,U007204,Robert Combs,Savannahview,2,8728.77,High Value
14,U001843,Latoya Torres,Port Catherine,3,8510.87,High Value
15,U006376,Susan Guerrero,West Nicholas,3,8406.65,High Value
16,U003718,Patricia Morgan,Patrickshire,4,8164.62,High Value
17,U007788,Justin Smith,Lake Kaitlin,2,8016.85,High Value
18,U000564,Kathryn Wong,Stevenland,7,7888.82,High Value
19,U003427,Tricia Gomez,West John,2,7879.77,High Value

## 9.2 Customer Segment Distribution

The number of customers in each segment is calculated to understand
the distribution of customer value.

In [63]:
# ============================================================
# STEP 9.2 - SEGMENT DISTRIBUTION
# ============================================================

segment_distribution = pd.read_sql_query(
    """

    WITH customer_spending AS (

        SELECT
            u.user_id,

            ROUND(SUM(oi.item_total), 2) AS total_spent

        FROM users AS u

        INNER JOIN orders AS o
            ON u.user_id = o.user_id

        INNER JOIN order_items AS oi
            ON o.order_id = oi.order_id

        GROUP BY
            u.user_id
    )


    SELECT

        CASE

            WHEN total_spent >= 5000
                THEN 'High Value'

            WHEN total_spent >= 2000
                THEN 'Medium Value'

            ELSE 'Low Value'

        END AS customer_segment,

        COUNT(*) AS customer_count,

        ROUND(
            SUM(total_spent),
            2
        ) AS segment_revenue

    FROM customer_spending

    GROUP BY
        customer_segment

    ORDER BY
        segment_revenue DESC;

    """,
    connection
)

display(segment_distribution)

  customer_segment  customer_count  segment_revenue
0     Medium Value            1816       5513921.46
1        Low Value            6582       4863219.67
2       High Value             234       1461162.82

# 10. Cohort Analysis and Customer Retention

Cohort analysis groups customers based on the month of their first order.

We then track whether these customers placed additional orders in
subsequent months.

This helps measure customer retention over time.

In [64]:
# ============================================================
# STEP 10.1 - CUSTOMER COHORT ANALYSIS
# ============================================================

cohort_analysis = pd.read_sql_query(
    """

    -- ========================================================
    -- CTE 1: Find the first order month for every customer
    -- ========================================================

    WITH customer_first_order AS (

        SELECT
            user_id,

            -- Find the month of customer's first order
            MIN(
                date(order_date)
            ) AS first_order_date

        FROM orders

        GROUP BY
            user_id
    ),


    -- ========================================================
    -- CTE 2: Get every customer's order month
    -- ========================================================

    customer_orders AS (

        SELECT
            o.user_id,

            date(o.order_date) AS order_date,

            c.first_order_date

        FROM orders AS o

        INNER JOIN customer_first_order AS c

            ON o.user_id = c.user_id
    )


    -- ========================================================
    -- Final cohort result
    -- ========================================================

    SELECT

        -- Month when the customer first purchased
        strftime(
            '%Y-%m',
            first_order_date
        ) AS cohort_month,

        -- Month when the customer made a purchase
        strftime(
            '%Y-%m',
            order_date
        ) AS order_month,

        -- Number of unique customers
        COUNT(
            DISTINCT user_id
        ) AS active_customers

    FROM customer_orders

    GROUP BY

        cohort_month,
        order_month

    ORDER BY

        cohort_month,
        order_month;

    """,
    connection
)

display(cohort_analysis.head(30))

   cohort_month order_month  active_customers
0       2024-01     2024-01               843
1       2024-01     2024-02                71
2       2024-01     2024-03                76
3       2024-01     2024-04                67
4       2024-01     2024-05                60
5       2024-01     2024-06                74
6       2024-01     2024-07                75
7       2024-01     2024-08                61
8       2024-01     2024-09                56
9       2024-01     2024-10                57
10      2024-01     2024-11                86
11      2024-01     2024-12                75
12      2024-01     2025-01                75
13      2024-01     2025-02                69
14      2024-01     2025-03                68
15      2024-01     2025-04                64
16      2024-01     2025-05                77
17      2024-01     2025-06                72
18      2024-01     2025-07                79
19      2024-01     2025-08                73
20      2024-01     2025-09                74
21      2024-01     2025-10                68
22      2024-01     2025-11                40
23      2024-02     2024-02               706
24      2024-02     2024-03                72
25      2024-02     2024-04                71
26      2024-02     2024-05                63
27      2024-02     2024-06                53
28      2024-02     2024-07                73
29      2024-02     2024-08                65

## 10.2 Calculate Months Since First Purchase

The retention month represents the number of months between the customer's
first purchase and a later purchase.

For example:

- Month 0 = First purchase
- Month 1 = Returned one month later
- Month 2 = Returned two months later
- Month 3 = Returned three months later

In [65]:
# ============================================================
# STEP 10.2 - RETENTION MONTH CALCULATION
# ============================================================

retention_analysis = pd.read_sql_query(
    """

    WITH customer_first_order AS (

        SELECT
            user_id,

            MIN(
                date(order_date)
            ) AS first_order_date

        FROM orders

        GROUP BY
            user_id
    ),


    customer_orders AS (

        SELECT
            o.user_id,

            date(o.order_date) AS order_date,

            c.first_order_date

        FROM orders AS o

        INNER JOIN customer_first_order AS c

            ON o.user_id = c.user_id
    )


    SELECT

        -- Customer's first order month
        strftime(
            '%Y-%m',
            first_order_date
        ) AS cohort_month,


        -- Month of the customer's order
        strftime(
            '%Y-%m',
            order_date
        ) AS order_month,


        -- Calculate months between first and current order
        (
            (
                CAST(
                    strftime('%Y', order_date)
                    AS INTEGER
                )
                -
                CAST(
                    strftime('%Y', first_order_date)
                    AS INTEGER
                )
            ) * 12
            +
            (
                CAST(
                    strftime('%m', order_date)
                    AS INTEGER
                )
                -
                CAST(
                    strftime('%m', first_order_date)
                    AS INTEGER
                )
            )
        ) AS retention_month,


        -- Number of active customers
        COUNT(
            DISTINCT user_id
        ) AS active_customers


    FROM customer_orders


    GROUP BY

        cohort_month,
        order_month,
        retention_month


    ORDER BY

        cohort_month,
        retention_month;

    """,
    connection
)

display(retention_analysis.head(30))

   cohort_month order_month  retention_month  active_customers
0       2024-01     2024-01                0               843
1       2024-01     2024-02                1                71
2       2024-01     2024-03                2                76
3       2024-01     2024-04                3                67
4       2024-01     2024-05                4                60
5       2024-01     2024-06                5                74
6       2024-01     2024-07                6                75
7       2024-01     2024-08                7                61
8       2024-01     2024-09                8                56
9       2024-01     2024-10                9                57
10      2024-01     2024-11               10                86
11      2024-01     2024-12               11                75
12      2024-01     2025-01               12                75
13      2024-01     2025-02               13                69
14      2024-01     2025-03               14                68
15      2024-01     2025-04               15                64
16      2024-01     2025-05               16                77
17      2024-01     2025-06               17                72
18      2024-01     2025-07               18                79
19      2024-01     2025-08               19                73
20      2024-01     2025-09               20                74
21      2024-01     2025-10               21                68
22      2024-01     2025-11               22                40
23      2024-02     2024-02                0               706
24      2024-02     2024-03                1                72
25      2024-02     2024-04                2                71
26      2024-02     2024-05                3                63
27      2024-02     2024-06                4                53
28      2024-02     2024-07                5                73
29      2024-02     2024-08                6                65

In [66]:
# ============================================================
# COHORT RETENTION RATE
# ============================================================

# Find the number of customers in each cohort's first month
# This will be our base customer count.
cohort_size = (
    retention_analysis[
        retention_analysis["retention_month"] == 0
    ][["cohort_month", "active_customers"]]
    .rename(columns={"active_customers": "cohort_size"})
)

# Merge cohort size with the retention analysis
retention_rate = retention_analysis.merge(
    cohort_size,
    on="cohort_month",
    how="left"
)

# Calculate retention percentage
retention_rate["retention_rate"] = (
    retention_rate["active_customers"]
    / retention_rate["cohort_size"]
    * 100
)

# Create a cohort retention matrix
cohort_matrix = retention_rate.pivot(
    index="cohort_month",
    columns="retention_month",
    values="retention_rate"
)

# Round percentages to 2 decimal places
cohort_matrix = cohort_matrix.round(2)

print("COHORT RETENTION RATE (%)")
display(cohort_matrix)

COHORT RETENTION RATE (%)

retention_month,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
cohort_month,,,,,,,,,,,,,,,,,,,,,,,
2024-01,100.00,8.42,9.02,7.95,7.12,8.78,8.90,7.24,6.64,6.76,10.20,8.90,8.90,8.19,8.07,7.59,9.13,8.54,9.37,8.66,8.78,8.07,4.74
2024-02,100.00,10.20,10.06,8.92,7.51,10.34,9.21,9.49,9.63,7.51,9.92,8.50,8.78,8.07,8.22,8.78,6.94,9.21,9.21,8.64,7.79,5.52,NaN
2024-03,100.00,9.34,7.13,8.95,8.69,6.49,8.69,9.99,9.08,9.60,7.78,7.26,7.39,7.91,9.08,9.34,9.60,7.78,8.04,7.91,4.02,NaN,NaN
2024-04,100.00,8.43,8.88,7.40,8.58,9.32,10.50,6.66,7.69,10.06,5.77,6.95,9.76,11.54,7.25,8.28,8.43,9.02,7.84,3.99,NaN,NaN,NaN
2024-05,100.00,9.42,7.95,9.25,9.42,6.17,9.58,6.98,8.60,7.95,7.95,7.95,9.90,9.09,8.60,8.77,7.14,8.77,3.57,NaN,NaN,NaN,NaN
2024-06,100.00,9.91,7.16,8.62,8.62,9.54,6.79,8.81,6.24,8.81,7.71,8.07,6.24,8.62,9.72,10.28,9.72,3.67,NaN,NaN,NaN,NaN,NaN
2024-07,100.00,8.70,7.96,8.33,7.78,7.22,8.15,10.74,8.33,6.30,7.41,7.59,8.33,8.89,6.85,8.70,3.70,NaN,NaN,NaN,NaN,NaN,NaN
2024-08,100.00,6.49,9.74,10.61,8.23,9.52,8.44,9.52,11.04,8.23,9.09,8.66,9.96,6.28,9.74,4.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-09,100.00,7.77,8.50,10.19,5.83,7.52,8.01,9.71,9.71,6.55,6.07,6.55,10.44,7.77,4.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-10,100.00,6.53,8.09,7.05,10.70,9.66,8.36,6.01,9.66,7.57,8.36,11.23,7.83,3.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-11,100.00,8.12,7.19,8.44,8.75,5.62,8.12,8.44,10.00,8.75,9.38,9.06,2.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024-12,100.00,8.82,6.47,9.71,5.59,9.71,8.24,5.59,9.71,11.47,7.94,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-01,100.00,7.46,7.46,10.85,10.85,10.17,8.47,10.17,10.85,8.14,2.37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-02,100.00,10.97,8.02,6.75,9.28,12.24,7.59,7.59,8.44,3.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03,100.00,12.65,7.35,9.39,7.35,8.16,5.71,11.43,2.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04,100.00,6.47,6.97,9.45,10.95,6.97,4.98,5.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05,100.00,14.21,12.69,6.60,8.12,11.17,2.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06,100.00,3.93,13.48,5.62,9.55,3.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-07,100.00,7.43,4.57,8.00,3.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-08,100.00,9.09,8.44,0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-09,100.00,6.49,3.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-10,100.00,3.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-11,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
# ============================================================
# CUSTOMER SEGMENTATION ANALYSIS
# ============================================================

# Create customer segments based on total spending
# Low Value    : less than 500
# Medium Value : 500 to 2000
# High Value   : more than 2000

customer_summary["customer_segment"] = pd.cut(
    customer_summary["total_spent"],
    bins=[-np.inf, 500, 2000, np.inf],
    labels=["Low Value", "Medium Value", "High Value"]
)

# Count customers and calculate revenue for each segment
segment_distribution = (
    customer_summary
    .groupby("customer_segment", observed=False)
    .agg(
        customer_count=("user_id", "count"),
        segment_revenue=("total_spent", "sum")
    )
    .reset_index()
)

# Round revenue
segment_distribution["segment_revenue"] = (
    segment_distribution["segment_revenue"].round(2)
)

print("CUSTOMER SEGMENT DISTRIBUTION")
display(segment_distribution)

CUSTOMER SEGMENT DISTRIBUTION

  customer_segment  customer_count  segment_revenue
0        Low Value            2804        637268.36
1     Medium Value            3778       4225951.31
2       High Value            2050       6975084.28

In [68]:
# ============================================================
# RFM ANALYSIS
# ============================================================
# RFM stands for:
# R = Recency    -> How recently the customer purchased
# F = Frequency  -> How many orders the customer made
# M = Monetary   -> How much the customer spent
# ============================================================

# Make sure order_date is in datetime format
orders_clean["order_date"] = pd.to_datetime(orders_clean["order_date"])

# Set the reference date as one day after the latest order
# This makes the recency calculation consistent with our dataset.
reference_date = orders_clean["order_date"].max() + pd.Timedelta(days=1)

# Calculate RFM values for every customer
rfm_analysis = (
    orders_clean
    .groupby("user_id")
    .agg(
        # Recency: days since the customer's most recent order
        recency=("order_date", lambda x:
                 (reference_date - x.max()).days),

        # Frequency: total number of orders
        frequency=("order_id", "nunique"),

        # Monetary: total amount spent
        monetary=("total_amount", "sum")
    )
    .reset_index()
)

# Round monetary value to 2 decimal places
rfm_analysis["monetary"] = rfm_analysis["monetary"].round(2)

print("RFM ANALYSIS")
display(rfm_analysis.head(10))

RFM ANALYSIS

   user_id  recency  frequency  monetary
0  U000001      569          1   1392.89
1  U000002      326          4   1808.15
2  U000003       25          3   1153.01
3  U000004       66          3   7620.84
4  U000005      300          1     12.66
5  U000006      102          6   9952.28
6  U000008      287          2   1520.91
7  U000009      254          1   1297.61
8  U000010      117          5   1631.68
9  U000011      423          2   1050.88

In [69]:
# ============================================================
# RFM SCORING
# ============================================================
# We assign each customer a score from 1 to 5.
#
# Recency:
#   Lower recency = better customer
#
# Frequency:
#   Higher frequency = better customer
#
# Monetary:
#   Higher spending = better customer
# ============================================================

# Recency score
# Recent customers get a higher score.
rfm_analysis["R_score"] = pd.qcut(
    rfm_analysis["recency"],
    q=5,
    labels=[5, 4, 3, 2, 1],
    duplicates="drop"
).astype(int)

# Frequency score
# Customers with more orders get a higher score.
rfm_analysis["F_score"] = pd.qcut(
    rfm_analysis["frequency"].rank(method="first"),
    q=5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Monetary score
# Customers who spend more get a higher score.
rfm_analysis["M_score"] = pd.qcut(
    rfm_analysis["monetary"],
    q=5,
    labels=[1, 2, 3, 4, 5],
    duplicates="drop"
).astype(int)

# Create one combined RFM score
rfm_analysis["RFM_score"] = (
    rfm_analysis["R_score"].astype(str)
    + rfm_analysis["F_score"].astype(str)
    + rfm_analysis["M_score"].astype(str)
)

print("RFM SCORES")
display(rfm_analysis.head(10))

RFM SCORES

   user_id  recency  frequency  monetary  R_score  F_score  M_score RFM_score
0  U000001      569          1   1392.89        1        1        4       114
1  U000002      326          4   1808.15        2        5        4       254
2  U000003       25          3   1153.01        5        4        3       543
3  U000004       66          3   7620.84        5        4        5       545
4  U000005      300          1     12.66        2        1        1       211
5  U000006      102          6   9952.28        4        5        5       455
6  U000008      287          2   1520.91        2        2        4       224
7  U000009      254          1   1297.61        3        1        4       314
8  U000010      117          5   1631.68        4        5        4       454
9  U000011      423          2   1050.88        1        2        3       123

In [70]:
# ============================================================
# FINAL RFM CUSTOMER SEGMENTS
# ============================================================
# We classify customers based on their combined RFM score.
#
# High Value Customer  -> Strong RFM score
# Medium Value Customer -> Average RFM score
# Low Value Customer   -> Lower RFM score
# ============================================================

# Convert individual scores into a numeric total
rfm_analysis["RFM_total"] = (
    rfm_analysis["R_score"]
    + rfm_analysis["F_score"]
    + rfm_analysis["M_score"]
)

# Create customer segments based on total RFM score
rfm_analysis["customer_segment"] = pd.cut(
    rfm_analysis["RFM_total"],
    bins=[0, 7, 11, 15],
    labels=["Low Value", "Medium Value", "High Value"],
    include_lowest=True
)

# Count customers in each segment
rfm_segments = (
    rfm_analysis
    .groupby("customer_segment", observed=False)
    .agg(
        customer_count=("user_id", "count"),
        total_revenue=("monetary", "sum")
    )
    .reset_index()
)

# Round revenue
rfm_segments["total_revenue"] = rfm_segments["total_revenue"].round(2)

print("FINAL RFM CUSTOMER SEGMENTS")
display(rfm_segments)

FINAL RFM CUSTOMER SEGMENTS

  customer_segment  customer_count  total_revenue
0        Low Value            3063     1372656.16
1     Medium Value            3267     4244576.95
2       High Value            2303     6266659.21

In [71]:
# ============================================================
# PRODUCT PERFORMANCE ANALYSIS
# ============================================================
# We will calculate:
# 1. Total quantity sold for each product
# 2. Total revenue generated by each product
# 3. Number of orders containing each product
# ============================================================

# Aggregate order item data by product
product_performance = (
    order_items_clean
    .groupby("product_id")
    .agg(
        total_quantity_sold=("quantity", "sum"),
        total_revenue=("item_total", "sum"),
        total_orders=("order_id", "nunique")
    )
    .reset_index()
)

# Add product names and categories
product_performance = product_performance.merge(
    products_clean[["product_id", "product_name", "category", "brand"]],
    on="product_id",
    how="left"
)

# Sort products by total revenue
product_performance = product_performance.sort_values(
    "total_revenue",
    ascending=False
)

# Round revenue
product_performance["total_revenue"] = (
    product_performance["total_revenue"].round(2)
)

print("TOP 10 PRODUCTS BY REVENUE")

display(
    product_performance[
        [
            "product_id",
            "product_name",
            "category",
            "brand",
            "total_quantity_sold",
            "total_orders",
            "total_revenue"
        ]
    ].head(10)
)

TOP 10 PRODUCTS BY REVENUE

,product_id,product_name,category,brand,total_quantity_sold,total_orders,total_revenue
1526,P001527,Willow Result,Electronics,Willow,35.00,22,71239.70
1023,P001024,Astra Pull,Electronics,Astra,28.00,19,65467.64
20,P000021,Willow Special,Electronics,Willow,35.00,25,62032.60
909,P000910,Orion Group,Electronics,Orion,26.00,21,60784.10
135,P000136,Zenith Phone,Electronics,Zenith,26.00,19,56419.48
1924,P001925,Willow Hospital,Automotive,Willow,42.00,30,56311.92
460,P000461,Nimbus Family,Electronics,Nimbus,32.00,24,54411.20
197,P000198,Orion Face,Electronics,Orion,40.00,29,54105.20
554,P000555,Acme Of,Electronics,Acme,38.00,27,53489.18
730,P000731,Pulse Treat,Electronics,Pulse,43.00,31,53166.06

In [72]:
# ============================================================
# CATEGORY PERFORMANCE ANALYSIS
# ============================================================
# We will calculate:
# 1. Number of products in each category
# 2. Total quantity sold
# 3. Total orders
# 4. Total revenue
# ============================================================

category_performance = (
    product_performance
    .groupby("category")
    .agg(
        product_count=("product_id", "nunique"),
        total_quantity_sold=("total_quantity_sold", "sum"),
        total_orders=("total_orders", "sum"),
        total_revenue=("total_revenue", "sum")
    )
    .reset_index()
)

# Sort categories by revenue
category_performance = category_performance.sort_values(
    "total_revenue",
    ascending=False
)

# Round revenue
category_performance["total_revenue"] = (
    category_performance["total_revenue"].round(2)
)

print("CATEGORY PERFORMANCE")

display(category_performance)

CATEGORY PERFORMANCE

,category,product_count,total_quantity_sold,total_orders,total_revenue
4,Electronics,203,5863.00,4226,4936846.91
0,Automotive,193,5903.00,4220,2492784.13
6,Home & Kitchen,199,5884.00,4214,1128015.62
8,Sports,183,5628.00,4036,947578.60
3,Clothing,213,6397.00,4592,709667.75
1,Beauty,207,6312.00,4534,554148.60
9,Toys,213,6503.00,4704,384283.54
7,Pet Supplies,212,6696.00,4716,353044.10
2,Books,194,6050.00,4298,273913.53
5,Groceries,183,5409.00,3856,89653.41

In [73]:
# ============================================================
# BRAND PERFORMANCE ANALYSIS
# ============================================================
# We will calculate:
# 1. Number of products for each brand
# 2. Total quantity sold
# 3. Total orders
# 4. Total revenue
# ============================================================

brand_performance = (
    product_performance
    .groupby("brand")
    .agg(
        product_count=("product_id", "nunique"),
        total_quantity_sold=("total_quantity_sold", "sum"),
        total_orders=("total_orders", "sum"),
        total_revenue=("total_revenue", "sum")
    )
    .reset_index()
)

# Sort brands by total revenue
brand_performance = brand_performance.sort_values(
    "total_revenue",
    ascending=False
)

# Round revenue
brand_performance["total_revenue"] = (
    brand_performance["total_revenue"].round(2)
)

print("TOP 10 BRANDS BY REVENUE")

display(brand_performance.head(10))

TOP 10 BRANDS BY REVENUE

        brand  product_count  total_quantity_sold  total_orders  total_revenue
10     Willow            165              5107.00          3696     1318849.08
7       Orion            163              5017.00          3633     1150790.77
6      Nimbus            182              5402.00          3808     1089432.73
0        Acme            155              4739.00          3330     1040443.85
1       Astra            165              4961.00          3567     1021515.96
11     Zenith            190              5856.00          4219     1007247.27
3   GreenLeaf            174              5357.00          3808      987052.94
4      Harbor            183              5346.00          3839      920372.07
9      Solace            156              4782.00          3455      888325.18
8       Pulse            147              4331.00          3072      877642.67

In [74]:
# ============================================
# 16. PRODUCTS FREQUENTLY BOUGHT TOGETHER
# ============================================

# Keep only required columns
pair_data = order_items_clean[['order_id', 'product_id']].copy()

# Remove duplicate products within the same order
pair_data = pair_data.drop_duplicates()

# Self-join on order_id to find products bought in the same order
product_pairs = pair_data.merge(
    pair_data,
    on='order_id'
)

# Remove same-product pairs
product_pairs = product_pairs[
    product_pairs['product_id_x'] != product_pairs['product_id_y']
]

# Keep each pair only once:
# A-B should be included, but B-A should not
product_pairs['product_a'] = product_pairs[['product_id_x', 'product_id_y']].min(axis=1)
product_pairs['product_b'] = product_pairs[['product_id_x', 'product_id_y']].max(axis=1)

# Count how many times each pair was bought together
frequent_pairs = (
    product_pairs
    .groupby(['product_a', 'product_b'])
    .size()
    .reset_index(name='times_bought_together')
    .sort_values('times_bought_together', ascending=False)
)

print("TOP PRODUCTS FREQUENTLY BOUGHT TOGETHER")

display(frequent_pairs.head(20))

TOP PRODUCTS FREQUENTLY BOUGHT TOGETHER

      product_a product_b  times_bought_together
28813   P000934   P001775                      6
30759   P001030   P001344                      6
34039   P001214   P001230                      6
34613   P001249   P001334                      6
13856   P000388   P001317                      4
8022    P000214   P001540                      4
18123   P000521   P001462                      4
17804   P000512   P000655                      4
15998   P000452   P001595                      4
6046    P000159   P000372                      4
4790    P000125   P000343                      4
6047    P000159   P000438                      4
11643   P000317   P001963                      4
17328   P000497   P000776                      4
9109    P000244   P001162                      4
3559    P000091   P001312                      4
10494   P000283   P001817                      4
12059   P000330   P001522                      4
7802    P000209   P000385                      4
13389   P000372   P000756                      4

# PART 4: PYTHON + SQL INTEGRATION

In [75]:
import sqlite3

# Create SQLite database
connection = sqlite3.connect("ecommerce.db")

print("SQLite database connected successfully!")

SQLite database connected successfully!

In [76]:
# Load cleaned datasets into SQLite

users_clean.to_sql(
    "users",
    connection,
    if_exists="replace",
    index=False
)

products_clean.to_sql(
    "products",
    connection,
    if_exists="replace",
    index=False
)

orders_clean.to_sql(
    "orders",
    connection,
    if_exists="replace",
    index=False
)

order_items_clean.to_sql(
    "order_items",
    connection,
    if_exists="replace",
    index=False
)

print("All clean datasets loaded into SQLite successfully!")

All clean datasets loaded into SQLite successfully!

In [6]:
# ============================================
# STEP 4: GET REPORT TYPE AND DATE RANGE
# ============================================

report_type = input("Enter report type (daily/weekly/monthly): ").strip().lower()

start_date = input("Enter start date (YYYY-MM-DD): ").strip()
end_date = input("Enter end date (YYYY-MM-DD): ").strip()

print("\nReport Details:")
print("Report Type:", report_type)
print("Start Date:", start_date)
print("End Date:", end_date)

Report Details:
Report Type: monthly
Start Date: 2024-01-01
End Date: 2024-12-31

In [8]:
import pandas as pd

In [10]:
import sqlite3

connection = sqlite3.connect("ecommerce.db")

print("SQLite connection successful!")

SQLite connection successful!

In [11]:
# ============================================
# STEP 4: GENERATE MONTHLY SALES REPORT
# ============================================

query = """
SELECT
    strftime('%Y-%m', o.order_date) AS order_month,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.item_total), 2) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE DATE(o.order_date) BETWEEN DATE(?) AND DATE(?)
GROUP BY strftime('%Y-%m', o.order_date)
ORDER BY order_month;
"""

monthly_report = pd.read_sql_query(
    query,
    connection,
    params=(start_date, end_date)
)

print("MONTHLY SALES REPORT")
display(monthly_report)

MONTHLY SALES REPORT

   order_month  total_orders  total_quantity_sold  total_revenue
0      2024-01           880               2653.0      542175.45
1      2024-02           807               2505.0      502933.09
2      2024-03           949               2818.0      537780.48
3      2024-04           923               2853.0      539439.56
4      2024-05           900               2724.0      545178.65
5      2024-06           895               2699.0      546121.51
6      2024-07           952               2910.0      583345.16
7      2024-08           879               2659.0      516802.40
8      2024-09           881               2627.0      524160.08
9      2024-10           895               2708.0      527608.85
10     2024-11           873               2600.0      510188.82
11     2024-12           914               2842.0      579209.81

In [13]:
import os

# Create reports folder if it does not exist
os.makedirs("reports", exist_ok=True)

# Save monthly report
monthly_report.to_csv(
    "reports/monthly_sales_report.csv",
    index=False
)

print("Monthly sales report saved successfully!")

Monthly sales report saved successfully!

In [14]:
# ============================================
# STEP 4: GENERATE WEEKLY SALES REPORT
# ============================================

query = """
SELECT
    strftime('%Y-%W', o.order_date) AS order_week,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.item_total), 2) AS total_revenue
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE o.order_date BETWEEN ? AND ?
GROUP BY order_week
ORDER BY order_week;
"""

weekly_report = pd.read_sql_query(
    query,
    connection,
    params=(start_date, end_date)
)

print("WEEKLY SALES REPORT")
display(weekly_report)

WEEKLY SALES REPORT

   order_week  total_orders  total_quantity_sold  total_revenue
0     2024-01           206                633.0      138998.07
1     2024-02           203                610.0      114932.81
2     2024-03           198                637.0      132051.16
3     2024-04           195                532.0      103190.85
4     2024-05           183                546.0      118820.21
5     2024-06           176                559.0      111301.75
6     2024-07           200                629.0      130614.44
7     2024-08           210                634.0      133723.20
8     2024-09           225                691.0      128703.78
9     2024-10           209                654.0      142343.91
10    2024-11           191                553.0      100942.13
11    2024-12           221                634.0      106091.84
12    2024-13           219                664.0      121174.87
13    2024-14           207                626.0      129937.11
14    2024-15           237                694.0      127088.62
15    2024-16           199                663.0      128635.84
16    2024-17           203                644.0      118727.31
17    2024-18           198                561.0      115836.26
18    2024-19           211                620.0      120188.40
19    2024-20           202                673.0      136325.39
20    2024-21           206                612.0      118619.01
21    2024-22           205                613.0      120307.06
22    2024-23           197                596.0      135388.99
23    2024-24           196                580.0      102744.01
24    2024-25           224                695.0      137558.44
25    2024-26           233                699.0      139383.28
26    2024-27           205                645.0      124745.53
27    2024-28           224                690.0      143766.87
28    2024-29           207                631.0      123022.30
29    2024-30           217                640.0      123396.75
30    2024-31           209                638.0      141453.15
31    2024-32           202                597.0      130092.12
32    2024-33           191                605.0      109805.79
33    2024-34           208                600.0      107466.27
34    2024-35           210                644.0      118279.51
35    2024-36           187                536.0       97612.89
36    2024-37           211                634.0      132557.76
37    2024-38           213                623.0      137126.73
38    2024-39           196                611.0      116435.70
39    2024-40           206                607.0      125551.08
40    2024-41           209                667.0      134390.07
41    2024-42           189                561.0      108198.96
42    2024-43           208                654.0      124450.60
43    2024-44           212                632.0      102974.60
44    2024-45           194                584.0      120732.89
45    2024-46           194                575.0      111752.35
46    2024-47           213                630.0      125140.12
47    2024-48           198                564.0      119630.11
48    2024-49           244                791.0      160115.90
49    2024-50           199                582.0      122941.78
50    2024-51           187                607.0      122178.59
51    2024-52           190                598.0      115590.51
52    2024-53            36                 92.0       21989.53

In [15]:
# Save weekly sales report

import os

os.makedirs("reports", exist_ok=True)

weekly_report.to_csv(
    "reports/weekly_sales_report.csv",
    index=False
)

print("Weekly sales report saved successfully!")

Weekly sales report saved successfully!

In [16]:

# Check SQLite tables and columns

import sqlite3

connection = sqlite3.connect("ecommerce.db")

tables = ["orders", "order_items", "products", "users"]

for table in tables:
    print(f"\n--- {table.upper()} ---")
    
    columns = connection.execute(
        f"PRAGMA table_info({table})"
    ).fetchall()
    
    for column in columns:
        print(column[1], "->", column[2])

--- ORDERS ---
order_id -> TEXT
user_id -> TEXT
order_date -> TIMESTAMP
order_status -> TEXT
total_amount -> REAL

--- ORDER_ITEMS ---
order_item_id -> TEXT
order_id -> TEXT
product_id -> TEXT
user_id -> TEXT
quantity -> REAL
item_price -> REAL
item_total -> REAL

--- PRODUCTS ---
product_id -> TEXT
product_name -> TEXT
category -> TEXT
brand -> TEXT
price -> REAL
rating -> REAL

--- USERS ---
user_id -> TEXT
name -> TEXT
email -> TEXT
gender -> TEXT
city -> TEXT
signup_date -> TIMESTAMP

In [17]:
# ============================================
# STEP 4: SALES SUMMARY REPORT
# ============================================

from datetime import datetime, timedelta

# Convert input dates to date objects
start = datetime.strptime(start_date, "%Y-%m-%d").date()
end = datetime.strptime(end_date, "%Y-%m-%d").date()

# Calculate previous period
period_days = (end - start).days + 1
previous_end = start - timedelta(days=1)
previous_start = previous_end - timedelta(days=period_days - 1)

# ============================================
# CURRENT PERIOD SUMMARY
# ============================================

summary_query = """
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    COALESCE(SUM(total_amount), 0) AS total_revenue,
    COUNT(DISTINCT user_id) AS unique_customers
FROM orders
WHERE DATE(order_date) BETWEEN ? AND ?
"""

summary = connection.execute(
    summary_query,
    (start_date, end_date)
).fetchone()

total_orders = summary[0]
total_revenue = summary[1]
unique_customers = summary[2]


# ============================================
# TOP 3 PRODUCTS
# ============================================

top_products_query = """
SELECT
    p.product_name,
    SUM(oi.quantity) AS quantity_sold,
    SUM(oi.item_total) AS product_revenue
FROM order_items oi
JOIN orders o
    ON oi.order_id = o.order_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE DATE(o.order_date) BETWEEN ? AND ?
GROUP BY p.product_id, p.product_name
ORDER BY product_revenue DESC
LIMIT 3
"""

top_products = connection.execute(
    top_products_query,
    (start_date, end_date)
).fetchall()


# ============================================
# PREVIOUS PERIOD SUMMARY
# ============================================

previous_query = """
SELECT
    COUNT(DISTINCT order_id) AS total_orders,
    COALESCE(SUM(total_amount), 0) AS total_revenue
FROM orders
WHERE DATE(order_date) BETWEEN ? AND ?
"""

previous = connection.execute(
    previous_query,
    (previous_start.isoformat(), previous_end.isoformat())
).fetchone()

previous_orders = previous[0]
previous_revenue = previous[1]


# ============================================
# CALCULATE % CHANGE
# ============================================

if previous_revenue != 0:
    revenue_change = (
        (total_revenue - previous_revenue)
        / previous_revenue
    ) * 100
else:
    revenue_change = 0

if previous_orders != 0:
    orders_change = (
        (total_orders - previous_orders)
        / previous_orders
    ) * 100
else:
    orders_change = 0


# ============================================
# PRINT FINAL REPORT
# ============================================

print("=" * 50)
print("           SALES SUMMARY REPORT")
print("=" * 50)

print(f"Report Type       : {report_type}")
print(f"Start Date        : {start_date}")
print(f"End Date          : {end_date}")

print("\nSUMMARY")
print(f"Total Orders      : {total_orders}")
print(f"Total Revenue     : {total_revenue:.2f}")
print(f"Unique Customers  : {unique_customers}")

print("\nTOP 3 PRODUCTS")

for i, product in enumerate(top_products, start=1):
    print(
        f"{i}. {product[0]} "
        f"| Quantity Sold: {product[1]:.0f} "
        f"| Revenue: {product[2]:.2f}"
    )

print("\nPREVIOUS PERIOD COMPARISON")
print(f"Previous Period   : {previous_start} to {previous_end}")
print(f"Revenue Change    : {revenue_change:+.2f}%")
print(f"Orders Change     : {orders_change:+.2f}%")

print("=" * 50)

==================================================
           SALES SUMMARY REPORT
==================================================
Report Type       : monthly
Start Date        : 2024-01-01
End Date          : 2024-12-31

SUMMARY
Total Orders      : 10758
Total Revenue     : 6481438.85
Unique Customers  : 6614

TOP 3 PRODUCTS
1. Zenith Phone | Quantity Sold: 20 | Revenue: 43399.60
2. Pulse Treat | Quantity Sold: 32 | Revenue: 39565.44
3. Harbor Onto | Quantity Sold: 31 | Revenue: 38030.18

PREVIOUS PERIOD COMPARISON
Previous Period   : 2022-12-31 to 2023-12-31
Revenue Change    : +0.00%
Orders Change     : +0.00%
==================================================

# ==========================================
# PART 5: EDGE CASE HANDLING
# ==========================================

In [20]:
# ==========================================
# PART 5: EDGE CASE HANDLING
# ==========================================

import sqlite3

# Connect to SQLite database
connection = sqlite3.connect("ecommerce.db")


# Test 1: order_items has an order_id not present in orders
def test_invalid_order_id():
    query = """
    SELECT COUNT(*)
    FROM order_items oi
    LEFT JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_id IS NULL;
    """

    result = connection.execute(query).fetchone()[0]

    if result == 0:
        print("Test 1 PASSED: No invalid order_id found.")
    else:
        print(f"Test 1: {result} invalid order_id(s) found.")


# Test 2: Check whether discount_percent > 100

def test_discount_greater_than_100():
    # Check which table contains discount_percent
    tables = connection.execute("""
        SELECT name
        FROM sqlite_master
        WHERE type = 'table';
    """).fetchall()

    found = False

    for table in tables:
        table_name = table[0]

        columns = connection.execute(
            f"PRAGMA table_info({table_name})"
        ).fetchall()

        column_names = [column[1] for column in columns]

        if "discount_percent" in column_names:
            found = True

            query = f"""
            SELECT COUNT(*)
            FROM {table_name}
            WHERE discount_percent > 100;
            """

            result = connection.execute(query).fetchone()[0]

            if result == 0:
                print("Test 2 PASSED: No discount greater than 100% found.")
            else:
                print(
                    f"Test 2: {result} record(s) have discount_percent > 100."
                )

            break

    if not found:
       print("Test 2: Not Applicable (discount_percent column is not available in this dataset).")


test_discount_greater_than_100()


# Test 3: quantity is 0
def test_zero_quantity():
    query = """
    SELECT COUNT(*)
    FROM order_items
    WHERE quantity = 0;
    """

    result = connection.execute(query).fetchone()[0]

    if result == 0:
        print("Test 3 PASSED: No order has quantity = 0.")
    else:
        print(f"Test 3: {result} record(s) have quantity = 0.")


# Test 4: order_date is in the future
def test_future_order_date():
    query = """
    SELECT COUNT(*)
    FROM orders
    WHERE DATE(order_date) > DATE('now');
    """

    result = connection.execute(query).fetchone()[0]

    if result == 0:
        print("Test 4 PASSED: No future order_date found.")
    else:
        print(f"Test 4: {result} order(s) have a future order_date.")


# Run all tests
print("EDGE CASE TEST RESULTS")
print("=" * 50)

test_invalid_order_id()
test_discount_greater_than_100()
test_zero_quantity()
test_future_order_date()

Test 2: Not Applicable (discount_percent column is not available in this dataset).
EDGE CASE TEST RESULTS
==================================================
Test 1: 109 invalid order_id(s) found.
Test 2: Not Applicable (discount_percent column is not available in this dataset).
Test 3 PASSED: No order has quantity = 0.
Test 4 PASSED: No future order_date found.